DROP VIEW TSO.V_PT_AS_CANOPY_SET;
CREATE VIEW TSO.V_PT_AS_CANOPY_SET
	AS
SELECT DISTINCT
    A.BIG_CANOPY_ID AS BIG_CANOPY_ID,
    A.BIG_CANOPY_CD,
    A.GROW_POINT_ID,
    B.PT_YEAR       AS BUSINESS_YEAR,
    B.MAIN_BED_AREA AS MAIN_BED_AREA, --育苗棚 母床面积
    B.SUB_BED_AREA  AS SUB_BED_AREA, --育苗棚 子床面积
    CASE
        WHEN F.C1='4'
        THEN '合作社'
        WHEN F.C1='5'
        THEN '烟农'
    END AS GROW_TYPE_NAME, --育苗点统育类型名称(播种指标计算播种密度分组用)
	G.NAME               AS CANOPY_TYPE_NAME, --育苗棚设施类型名称(播种指标计算播种密度分组用)
    A.ORG_UNIQUE_CD AS ORG_CD,
    ''              AS SSTC,
    ''              AS SSTC_NAME,
    ''              AS STAC,
    ''              AS STAC_NAME,
    C.ORG_CD        AS COUC,
    C.ORG_ABBR      AS COUC_NAME,
    D.ORG_CD        AS CITC,
    D.ORG_ABBR      AS CITC_NAME,
    E.ORG_CD        AS PROV,
    E.ORG_ABBR      AS PROV_NAME,
    A.SEND_STATE,
    A.DATA_STATE,
    A.MODIFY_TIME,
    A.LAST_TIME
FROM
    TP_BIG_CANOPY A
LEFT JOIN
    PT_AS_CANOPY_SET B ON A.BIG_CANOPY_ID=B.CANOPY_ID
    /*烟点信息*/
LEFT JOIN
    CM_OM_ORG_MAIN C ON A.ORG_UNIQUE_CD = C.ORG_UNIQUE_CD
LEFT JOIN
    CM_OM_ORG_MAIN D ON C.CITY_UNIQUE_CD = D.ORG_UNIQUE_CD
LEFT JOIN
    CM_OM_ORG_MAIN E ON C.PROV_UNIQUE_CD = E.ORG_UNIQUE_CD
LEFT JOIN
    PT_DC_STAT_DATA_B F ON A.BIG_CANOPY_ID = F.CLT_OBJ_ID AND F.DATA_STATE='1'AND F.BILL_NO = 'TJ23000000000019'
LEFT JOIN
    CM_OT_ENUM_TYPE G ON A.BIG_CANOPY_TYPE_CD = G.ENUM_KEY
WHERE
    A.DATA_state='1'
AND A.USE_TYPE='PT'
AND B.data_state='1'
AND C.DATA_STATE='1'
AND C.END_YEAR=9999
AND D.DATA_STATE='1'
AND D.END_YEAR=9999
AND E.DATA_STATE='1'
AND E.END_YEAR=9999
    /*育苗棚设施类型枚举*/
AND G.DATA_STATE='1'
AND G.ENUM_TYPE_CD = 'CANOPY_TYPE_EK';

--在DCCELL库执行， 创建视图NICKNAME到DCCELL      
DROP NICKNAME DCCELL.V_PT_AS_CANOPY_SET;
CREATE NICKNAME DCCELL.V_PT_AS_CANOPY_SET FOR TSOSERVER.TSO.V_PT_AS_CANOPY_SET;   