DROP VIEW V_PT_BAK_TOBA_TRANS;
CREATE VIEW V_PT_BAK_TOBA_TRANS
   AS
SELECT DISTINCT
    A.TRANSPLANT_CB_D_ID AS ID,
    A.BUSINESS_YEAR,
    A.BUSINESS_DATE,
    B.PLAN_WEIGHT, --收购计划量
    C.FARMER_NUM, --烟农户数
    B.PLNT_AREA, --计划面积
    A.TRANSPLANT_AREA, --移栽面积
    CASE
        WHEN A.TRANSPLANT_AREA > 0
        AND B.PLNT_AREA > 0
        THEN CAST(ROUND(CAST(A.TRANSPLANT_AREA AS FLOAT)/B.PLNT_AREA,2) AS DECIMAL(10,2))
        ELSE 0
    END AS TRANS_PROP, --移栽占比
    A.TRANSPLANT_QTY, --移栽株数
    CASE
        WHEN A.TRANSPLANT_QTY > 0
        AND A.TRANSPLANT_AREA > 0
        THEN CAST(ROUND(CAST(A.TRANSPLANT_QTY AS FLOAT)/A.TRANSPLANT_AREA,2) AS DECIMAL(10,2))
        ELSE 0
    END AS PER_QTY, --亩占株数
    A.ORG_CD,
    A.ORG_NAME,
    A.PROV,
    A.PROV_NAME,
    A.CITC,
    A.CITC_NAME,
    A.COUC,
    A.COUC_NAME,
    A.STAC,
    A.STAC_NAME,
    A.SSTC,
    A.SSTC_NAME
FROM
    R_PT_TRANSPLANT_CB_D A
LEFT JOIN
    R_PC_PLAN_CB_Y B ON A.SSTC=B.SSTC
LEFT JOIN
    (
        SELECT
            SSTC,
            BUSINESS_YEAR,
            COUNT(1) AS FARMER_NUM
        FROM
            R_FARMER
        WHERE
            DATA_STATE='1'
        GROUP BY
            SSTC,
            BUSINESS_YEAR) C ON A.SSTC=C.SSTC
WHERE
    A.DATA_STATE='1'
AND B.DATA_STATE='1'
AND A.BUSINESS_YEAR=B.BUSINESS_YEAR
AND A.BUSINESS_YEAR=C.BUSINESS_YEAR