--小培土明细
SELECT
  A.TOWN_NAME,
  A.VAGE_NAME,
  A.FARMER_CD,
  A.FARMER_NAME,
  B.CNTRCT_PLNT_AREA,
  A.PTSX_AREA,
  CASE
  WHEN A.PTSX_AREA > 0
       AND B.CNTRCT_PLNT_AREA > 0
    THEN CAST(ROUND(CAST(A.PTSX_AREA * 100 AS FLOAT) / B.CNTRCT_PLNT_AREA, 2) AS DECIMAL(10, 2))
  ELSE 0
  END,
  CASE A.IS_HIGH_STAND
  WHEN '1'
    THEN '是'
  WHEN '0'
    THEN '否'
  ELSE 0 END     AS IS_STAND,
  CASE WORK_EFFECT_EVAL
  WHEN '01'
    THEN '好'
  WHEN '02'
    THEN '较好'
  WHEN '03'
    THEN '一般'
  WHEN '04'
    THEN '差' END AS EVAL,
  A.BEGIN_DATE,
  A.END_DATE,
  C.TECHNICIAN_NAME
FROM
  V_PT_SMALL_PTSX A
  LEFT JOIN
  (
    SELECT
      FARMER_CD,
      SUM(CNTRCT_PLNT_AREA) AS CNTRCT_PLNT_AREA
    FROM
      R_PC_CTRT_PC_Y_Y19
    WHERE DATA_STATE = '1'
    GROUP BY FARMER_CD
  ) B ON A.FARMER_CD = B.FARMER_CD
  LEFT JOIN
  R_TECHNICIAN_Y19 C
    ON A.TECHNICIAN_ID = C.TECHNICIAN_ID