--小培土
SELECT
  ORG.ORG_NAME,
  BC.TOTLE_FRM_QTY,
  BC.COMP_FRM_QTY,
  CASE
  WHEN BC.COMP_FRM_QTY > 0
       AND BC.TOTLE_FRM_QTY > 0
    THEN CAST(ROUND(CAST(BC.COMP_FRM_QTY * 100 AS FLOAT) / BC.TOTLE_FRM_QTY, 2) AS DECIMAL(10, 2))
  ELSE 0
  END,
  BC.CNTRCT_PLNT_AREA,
  A.PTSX_AREA,
  CASE
  WHEN A.PTSX_AREA > 0
       AND BC.CNTRCT_PLNT_AREA > 0
    THEN CAST(ROUND(CAST(A.PTSX_AREA * 100 AS FLOAT) / BC.CNTRCT_PLNT_AREA, 2) AS DECIMAL(10, 2))
  ELSE 0
  END,
  STAND_T,
  STAND_F,
  EVAL_1,
  EVAL_2,
  EVAL_3,
  BEGIN_DATE,
  END_DATE,
  A.ORG_CD
FROM
  (
    SELECT
      CITC            AS ORG_CD,
      SUM(PTSX_AREA)  AS PTSX_AREA,
      SUM(CASE WHEN IS_HIGH_STAND = '1'
        THEN PTSX_AREA
          ELSE 0 END) AS STAND_T,
      SUM(CASE WHEN IS_HIGH_STAND = '0'
        THEN PTSX_AREA
          ELSE 0 END) AS STAND_F,
      SUM(CASE
          WHEN WORK_EFFECT_EVAL = '01'
            THEN PTSX_AREA
          ELSE 0 END) AS EVAL_1,
      SUM(CASE
          WHEN WORK_EFFECT_EVAL = '02'
            THEN PTSX_AREA
          ELSE 0 END) AS EVAL_2,
      SUM(CASE
          WHEN WORK_EFFECT_EVAL = '03'
            THEN PTSX_AREA
          ELSE 0 END) AS EVAL_3,
      SUM(CASE
          WHEN WORK_EFFECT_EVAL = '04'
            THEN PTSX_AREA
          ELSE 0 END) AS EVAL_4,
      MIN(BEGIN_DATE) AS BEGIN_DATE,
      MAX(END_DATE)   AS END_DATE
    FROM
      V_PT_SMALL_PTSX
    WHERE
      DATA_STATE = '1'
      AND PROV = '52'
      AND BEGIN_DATE >= TIMESTAMP('2018-01-01 00:00:00')
      AND END_DATE <= TIMESTAMP('2019-05-09 00:00:00')
      AND BUSINESS_YEAR = 2019
    GROUP BY
      CITC) A
  LEFT JOIN
  (
    SELECT
      B.ORG_CD,
      COUNT(DISTINCT B.FARMER_CD) AS TOTLE_FRM_QTY,
      SUM(B.PTSX_AREA)            AS PTSX_AREA,
      SUM(C.CNTRCT_PLNT_AREA)     AS CNTRCT_PLNT_AREA,
      COUNT(DISTINCT (
        CASE
        WHEN B.PTSX_AREA = C.CNTRCT_PLNT_AREA
          THEN B.FARMER_CD
        END))                     AS COMP_FRM_QTY
    FROM
      (
        SELECT
          CITC           AS ORG_CD,
          FARMER_CD,
          SUM(PTSX_AREA) AS PTSX_AREA
        FROM
          V_PT_PUT_FERTILIZ
        WHERE
          DATA_STATE = '1'
          AND PROV = '52'
          AND BEGIN_DATE >= TIMESTAMP('2018-01-01 00:00:00')
          AND END_DATE <= TIMESTAMP('2019-05-09 00:00:00')
          AND BUSINESS_YEAR = 2019
        GROUP BY
          CITC, FARMER_CD
      ) B
      LEFT JOIN
      (
        SELECT
          FARMER_CD,
          SUM(CNTRCT_PLNT_AREA) AS CNTRCT_PLNT_AREA
        FROM
          R_PC_CTRT_PC_Y_Y19
        WHERE DATA_STATE = '1'
        GROUP BY FARMER_CD
      ) C ON B.FARMER_CD = C.FARMER_CD
    GROUP BY B.ORG_CD
  ) BC ON A.ORG_CD = BC.ORG_CD
  LEFT JOIN B_ORG ORG ON A.ORG_CD = ORG.ORG_CD