--施肥明细

SELECT
  A.TOWN_NAME,
  A.VAGE_NAME,
  A.FARMER_CD,
  A.FARMER_NAME,
  B.CNTRCT_PLNT_AREA,
  A.FERTILIZ_AREA,
  CASE
  WHEN A.FERTILIZ_AREA > 0
       AND B.CNTRCT_PLNT_AREA > 0
    THEN CAST(ROUND(CAST(A.FERTILIZ_AREA * 100 AS FLOAT) / B.CNTRCT_PLNT_AREA, 2) AS DECIMAL(10, 2))
  ELSE 0
  END,
  CASE WHEN A.IS_MEAL = '1'
    THEN '是'
  WHEN A.IS_MEAL = '0'
    THEN '否'
  ELSE 0 END AS IS_MEAL,
  CASE WHEN A.FERTILIZ_STAND = '1'
    THEN '正常'
  WHEN A.FERTILIZ_STAND = '2'
    THEN '偏高'
  WHEN A.FERTILIZ_STAND = '3'
    THEN '偏低'
  ELSE 0 END AS FERTILIZ_STAND,
  A.BEGIN_DATE,
  A.END_DATE,
  C.TECHNICIAN_NAME
FROM
  V_PT_PUT_FERTILIZ A
  LEFT JOIN
  (
    SELECT
      FARMER_CD,
      SUM(CNTRCT_PLNT_AREA) AS CNTRCT_PLNT_AREA
    FROM
      R_PC_CTRT_PC_Y_Y19
    WHERE DATA_STATE = '1'
    GROUP BY FARMER_CD
  ) B ON A.FARMER_CD = B.FARMER_CD
  LEFT JOIN
  R_TECHNICIAN_Y19 C
    ON A.TECHNICIAN_ID = C.TECHNICIAN_ID