--施肥

SELECT
  ORG.ORG_NAME,
  BC.TOTLE_FRM_QTY,
  BC.COMP_FRM_QTY,
  CASE
  WHEN BC.COMP_FRM_QTY > 0
       AND BC.TOTLE_FRM_QTY > 0
    THEN CAST(ROUND(CAST(BC.COMP_FRM_QTY * 100 AS FLOAT) / BC.TOTLE_FRM_QTY, 2) AS DECIMAL(10, 2))
  ELSE 0
  END,
  BC.CNTRCT_PLNT_AREA,
  A.FERTILIZ_AREA,
  CASE
  WHEN A.FERTILIZ_AREA > 0
       AND BC.CNTRCT_PLNT_AREA > 0
    THEN CAST(ROUND(CAST(A.FERTILIZ_AREA * 100 AS FLOAT) / BC.CNTRCT_PLNT_AREA, 2) AS DECIMAL(10, 2))
  ELSE 0
  END,
  MEAL_T,
  MEAL_F,
  STAND_1,
  STAND_2,
  STAND_3,
  BEGIN_DATE,
  END_DATE,
  A.ORG_CD
FROM
  (SELECT
     CITC               AS ORG_CD,
     SUM(FERTILIZ_AREA) AS FERTILIZ_AREA,
     SUM(CASE WHEN IS_MEAL = '1'
       THEN FERTILIZ_AREA
         ELSE 0 END)    AS MEAL_T,
     SUM(CASE WHEN IS_MEAL = '0'
       THEN FERTILIZ_AREA
         ELSE 0 END)    AS MEAL_F,
     SUM(CASE WHEN FERTILIZ_STAND = '1'
       THEN FERTILIZ_AREA
         ELSE 0 END)    AS STAND_1,
     SUM(CASE WHEN FERTILIZ_STAND = '2'
       THEN FERTILIZ_AREA
         ELSE 0 END)    AS STAND_2,
     SUM(CASE WHEN FERTILIZ_STAND = '3'
       THEN FERTILIZ_AREA
         ELSE 0 END)    AS STAND_3,
     MIN(BEGIN_DATE)    AS BEGIN_DATE,
     MAX(END_DATE)      AS END_DATE
   FROM
     V_PT_PUT_FERTILIZ
   WHERE
     DATA_STATE = '1'
     AND PROV = '52'
     AND BEGIN_DATE >= TIMESTAMP('2018-01-01 00:00:00')
     AND END_DATE <= TIMESTAMP('2019-05-09 00:00:00')
     AND BUSINESS_YEAR = 2019
   GROUP BY
     CITC) A
  LEFT JOIN
  (
    SELECT
      B.ORG_CD,
      COUNT(DISTINCT B.FARMER_CD) AS TOTLE_FRM_QTY,
      SUM(B.FERTILIZ_AREA)        AS FERTILIZ_AREA,
      SUM(C.CNTRCT_PLNT_AREA)     AS CNTRCT_PLNT_AREA,
      COUNT(DISTINCT (
        CASE
        WHEN B.FERTILIZ_AREA = C.CNTRCT_PLNT_AREA
          THEN B.FARMER_CD
        END))                     AS COMP_FRM_QTY
    FROM
      (
        SELECT
          CITC               AS ORG_CD,
          FARMER_CD,
          SUM(FERTILIZ_AREA) AS FERTILIZ_AREA
        FROM
          V_PT_PUT_FERTILIZ
        WHERE
          DATA_STATE = '1'
          AND PROV = '52'
          AND BEGIN_DATE >= TIMESTAMP('2018-01-01 00:00:00')
          AND END_DATE <= TIMESTAMP('2019-05-09 00:00:00')
          AND BUSINESS_YEAR = 2019
        GROUP BY
          CITC,FARMER_CD
      ) B
      LEFT JOIN
      (
        SELECT
          FARMER_CD,
          SUM(CNTRCT_PLNT_AREA) AS CNTRCT_PLNT_AREA
        FROM
          R_PC_CTRT_PC_Y_Y19
        WHERE DATA_STATE = '1'
        GROUP BY FARMER_CD
      ) C ON B.FARMER_CD = C.FARMER_CD
    GROUP BY B.ORG_CD
  ) BC ON A.ORG_CD = BC.ORG_CD
  LEFT JOIN B_ORG ORG ON A.ORG_CD = ORG.ORG_CD