
--DROP VIEW TSO.V_PT_BIG_PTSX;
CREATE VIEW TSO.V_PT_BIG_PTSX
  AS
 SELECT 
DATA_STORE_BASE_TBL_ID AS BIG_PTSX_ID,--ID
CLT_OBJ_ID AS FARMER_ID,--对应烟农ID
CLT_OBJ_CD AS FARMER_CD,--对应烟农CD
CLT_OBJ_NAME AS FARMER_NAME,--对应烟农名称
FEEDBACK_DATE AS BUSINESS_DATE,--采集日期
PT_YEAR AS BUSINESS_YEAR,--生产年度
D1 AS BEGIN_DATE,--开始日期
D2 AS END_DATE,--结束日期
N1 AS PTSX_AREA,--培土面积
C1 AS IS_HIGH_STAND,--垄高高度是否达到标准
C1.ENUM_NAME AS IS_HIGH_STAND_NAME,--垄高高度是否达到标准_显示名称
C2 AS WORK_EFFECT_EVAL,--实施效果评价
C2.ENUM_NAME AS WORK_EFFECT_EVAL_NAME,--实施效果评价_显示名称
C9.STATION_UNIQUE_CD AS ORG_CD,--组织单位
C9.DIVISION_UNIQUE_CD AS AREA_CD,--行政区划,
B1.PROV,
B1.PROV_NAME,
B1.CITC,
B1.CITC_NAME,
B1.COUC,
B1.COUC_NAME,
B1.STAC,
B1.STAC_NAME,
B1.SSTC,
B1.SSTC_NAME,
B1.SLIN,
B1.SLIN_NAME,
B1.ORG_NAME,
B2.AREA_PROV,
B2.AREA_PROV_NAME,
B2.AREA_CITC,
B2.AREA_CITC_NAME,
B2.AREA_COUC,
B2.AREA_COUC_NAME,
B2.AREA_TOWN,
B2.TOWN_NAME,
B2.AREA_VAGE,
B2.VAGE_NAME,
B2.AREA_GRUP,
B2.GRUP_NAME,
B2.ORG_NAME AS AREA_NAME,
 A.DATA_STATE  
  FROM PT_DC_STAT_DATA_E A 
      LEFT JOIN PT_IX_ENUM_DATA C2 ON C2.ENUM_CD = A.C2 AND C2.IDX_ID = '8a3c345369b94fd80169b9b9801e00a9' AND C2.DATA_STATE='1'
      LEFT JOIN PT_IX_ENUM_DATA C1 ON C1.ENUM_CD = A.C1 AND C1.IDX_ID = '8a3c36db4fd1aee7014ff31467e9000a' AND C1.DATA_STATE='1'
      LEFT JOIN CM_PM_FRM_FUND C9 ON C9.FRM_FUND_UNIQUE_ID = A.CLT_OBJ_ID AND C9.BIZ_YEAR = A.PT_YEAR AND C9.DATA_STATE = '1'
      LEFT JOIN B_ORG B1 ON C9.STATION_UNIQUE_CD = B1.ORG_UNIQUE_CD 
      LEFT JOIN B_DIVISION B2 ON  C9.DIVISION_UNIQUE_CD  = B2.DIVISION_UNIQUE_CD  
 WHERE 1=1 
   AND A.BILL_NO = 'TJHNCD0000000009'
   AND A.CHECK_STATE = '1'   
 ;
 

 
 
--DROP VIEW TSO.V_PT_DT_FM_D;
CREATE VIEW TSO.V_PT_DT_FM_D
  AS
 SELECT 
DATA_STORE_BASE_TBL_ID AS DT_FM_D_ID,--ID
CLT_OBJ_ID AS FARMER_ID,--对应烟农ID
CLT_OBJ_CD AS FARMER_CD,--对应烟农CD
CLT_OBJ_NAME AS FARMER_NAME,--对应烟农名称
FEEDBACK_DATE AS BUSINESS_DATE,--采集日期
PT_YEAR AS BUSINESS_YEAR,--生产年度
D1 AS BEGIN_DATE,--开始日期
D2 AS END_DATE,--结束日期
N1 AS BEAT_TOP_AREA,--打顶面积
C1 AS BEAT_TOP_OPPORT,--打顶时机
C1.ENUM_NAME AS BEAT_TOP_OPPORT_NAME,--打顶时机_显示名称
C2 AS BEAT_TOP_LEAF_QTY_EK,--打顶后有效叶数
C2.ENUM_NAME AS BEAT_TOP_LEAF_QTY_EK_NAME,--打顶后有效叶数_显示名称
C3 AS WORK_EFFECT_EVAL,--实施效果评价
C3.ENUM_NAME AS WORK_EFFECT_EVAL_NAME,--实施效果评价_显示名称
C9.STATION_UNIQUE_CD AS ORG_CD,--组织单位
C9.DIVISION_UNIQUE_CD AS AREA_CD,--行政区划,
 A.DATA_STATE 
  FROM PT_DC_STAT_DATA_B A 
      LEFT JOIN PT_IX_ENUM_DATA C1 ON C1.ENUM_CD = A.C1 AND C1.IDX_ID = '8a3c34536a8cad24016a950d945b0053' AND C1.DATA_STATE='1'
      LEFT JOIN PT_IX_ENUM_DATA C2 ON C2.ENUM_CD = A.C2 AND C2.IDX_ID = '8a3c34536a8cad24016a950e7aa00057' AND C2.DATA_STATE='1'
      LEFT JOIN PT_IX_ENUM_DATA C3 ON C3.ENUM_CD = A.C3 AND C3.IDX_ID = '8a3c345369b94fd80169b9b9801e00a9' AND C3.DATA_STATE='1'
      LEFT JOIN CM_PM_FRM_FUND C9 ON C9.FRM_FUND_UNIQUE_ID = A.CLT_OBJ_ID AND C9.BIZ_YEAR = A.PT_YEAR AND C9.DATA_STATE = '1' 
 WHERE 1=1 
   AND A.BILL_NO = 'TJHNCD0000000015'
   AND A.CHECK_STATE = '1'   
 ;
 
 
 
 
--DROP VIEW TSO.V_PT_OPTM_STRU;
CREATE VIEW TSO.V_PT_OPTM_STRU
  AS
 SELECT 
DATA_STORE_BASE_TBL_ID AS OPTM_STRU_ID,--ID
CLT_OBJ_ID AS FARMER_ID,--对应烟农ID
CLT_OBJ_CD AS FARMER_CD,--对应烟农CD
CLT_OBJ_NAME AS FARMER_NAME,--对应烟农名称
FEEDBACK_DATE AS BUSINESS_DATE,--采集日期
PT_YEAR AS BUSINESS_YEAR,--生产年度
D1 AS BEGIN_DATE,--开始日期
D2 AS END_DATE,--结束日期
N1 AS OPTM_AREA,--优化结构面积
C1 AS GIVE_UP_BOTTOM,--打掉下部
C1.ENUM_NAME AS GIVE_UP_BOTTOM_NAME,--打掉下部_显示名称
C2 AS GIVE_UP_TOP,--弃采上部
C2.ENUM_NAME AS GIVE_UP_TOP_NAME,--弃采上部_显示名称
C3 AS WORK_EFFECT_EVAL,--实施效果评价
C3.ENUM_NAME AS WORK_EFFECT_EVAL_NAME,--实施效果评价_显示名称
C9.STATION_UNIQUE_CD AS ORG_CD,--组织单位
C9.DIVISION_UNIQUE_CD AS AREA_CD,--行政区划,
B1.PROV,
B1.PROV_NAME,
B1.CITC,
B1.CITC_NAME,
B1.COUC,
B1.COUC_NAME,
B1.STAC,
B1.STAC_NAME,
B1.SSTC,
B1.SSTC_NAME,
B1.SLIN,
B1.SLIN_NAME,
B1.ORG_NAME,
B2.AREA_PROV,
B2.AREA_PROV_NAME,
B2.AREA_CITC,
B2.AREA_CITC_NAME,
B2.AREA_COUC,
B2.AREA_COUC_NAME,
B2.AREA_TOWN,
B2.TOWN_NAME,
B2.AREA_VAGE,
B2.VAGE_NAME,
B2.AREA_GRUP,
B2.GRUP_NAME,
B2.ORG_NAME AS AREA_NAME,
 A.DATA_STATE  
  FROM PT_DC_STAT_DATA_G A 
      LEFT JOIN PT_IX_ENUM_DATA C2 ON C2.ENUM_CD = A.C2 AND C2.IDX_ID = '8a3c34536a8cad24016a950ccb18004f' AND C2.DATA_STATE='1'
      LEFT JOIN CM_PM_FRM_FUND C9 ON C9.FRM_FUND_UNIQUE_ID = A.CLT_OBJ_ID AND C9.BIZ_YEAR = A.PT_YEAR AND C9.DATA_STATE = '1'
      LEFT JOIN PT_IX_ENUM_DATA C3 ON C3.ENUM_CD = A.C3 AND C3.IDX_ID = '8a3c345369b94fd80169b9b9801e00a9' AND C3.DATA_STATE='1'
      LEFT JOIN PT_IX_ENUM_DATA C1 ON C1.ENUM_CD = A.C1 AND C1.IDX_ID = '8a3c34536a8cad24016a950c12d2004a' AND C1.DATA_STATE='1'
      LEFT JOIN B_ORG B1 ON C9.STATION_UNIQUE_CD = B1.ORG_UNIQUE_CD 
      LEFT JOIN B_DIVISION B2 ON  C9.DIVISION_UNIQUE_CD  = B2.DIVISION_UNIQUE_CD  
 WHERE 1=1 
   AND A.BILL_NO = 'TJHNCD0000000013'
   AND A.CHECK_STATE = '1'   
 ;
 
 


--DROP VIEW TSO.V_PT_PLOUGH_FM_D;
CREATE VIEW TSO.V_PT_PLOUGH_FM_D
  AS
 SELECT 
DATA_STORE_BASE_TBL_ID AS PLOUGH_FM_D_ID,--ID
CLT_OBJ_ID AS FARMER_ID,--对应烟农ID
CLT_OBJ_CD AS FARMER_CD,--对应烟农CD
CLT_OBJ_NAME AS FARMER_NAME,--对应烟农名称
FEEDBACK_DATE AS BUSINESS_DATE,--采集日期
PT_YEAR AS BUSINESS_YEAR,--生产年度
D1 AS END_DATE,--结束日期
N1 AS PLOUGH_AREA,--翻耕面积
C1 AS IS_DEPTH_STAND,--翻耕深度是否达到标准
C1.ENUM_NAME AS IS_DEPTH_STAND_NAME,--翻耕深度是否达到标准_显示名称
C2 AS IS_OPEN_TRENCH,--是否打开腰围沟
C2.ENUM_NAME AS IS_OPEN_TRENCH_NAME,--是否打开腰围沟_显示名称
C3 AS IS_PROPESS,--是否专业化服务
C3.ENUM_NAME AS IS_PROPESS_NAME,--是否专业化服务_显示名称
C4 AS WORK_EFFECT_EVAL,--实施效果评价
C4.ENUM_NAME AS WORK_EFFECT_EVAL_NAME,--实施效果评价_显示名称
C5 AS SERV_ORG_ID,--服务队ID
C9.STATION_UNIQUE_CD AS ORG_CD,--组织单位
C9.DIVISION_UNIQUE_CD AS AREA_CD,--行政区划,
 A.DATA_STATE 
  FROM PT_DC_STAT_DATA_A A 
      LEFT JOIN PT_IX_ENUM_DATA C4 ON C4.ENUM_CD = A.C4  AND C4.IDX_ID = '8a3c345369b94fd80169b9b9801e00a9' AND C4.DATA_STATE='1'
      LEFT JOIN CM_PM_FRM_FUND C9 ON C9.FRM_FUND_UNIQUE_ID = A.CLT_OBJ_ID AND C9.BIZ_YEAR = A.PT_YEAR AND C9.DATA_STATE = '1'
      LEFT JOIN PT_IX_ENUM_DATA C3 ON C3.ENUM_CD = A.C3  AND C3.IDX_ID = '8a3c36db4fd1aee7014ff31467e9000a' AND C3.DATA_STATE='1'
      LEFT JOIN PT_IX_ENUM_DATA C1 ON C1.ENUM_CD = A.C1  AND C1.IDX_ID = '8a3c36db4fd1aee7014ff31467e9000a' AND C1.DATA_STATE='1'
      LEFT JOIN PT_IX_ENUM_DATA C2 ON C2.ENUM_CD = A.C2  AND C2.IDX_ID = '8a3c36db4fd1aee7014ff31467e9000a' AND C2.DATA_STATE='1' 
 WHERE 1=1 
   AND A.BILL_NO = 'TJHNCD0000000001'
   AND A.CHECK_STATE = '1'   
 ;
 
 
 
 
 --DROP VIEW TSO.V_PT_PREPAR_FM_D;
CREATE VIEW TSO.V_PT_PREPAR_FM_D
  AS
 SELECT 
DATA_STORE_BASE_TBL_ID AS PREPAR_FM_D_ID,--ID
CLT_OBJ_ID AS FARMER_ID,--对应烟农ID
CLT_OBJ_CD AS FARMER_CD,--对应烟农CD
CLT_OBJ_NAME AS FARMER_NAME,--对应烟农名称
FEEDBACK_DATE AS BUSINESS_DATE,--采集日期
PT_YEAR AS BUSINESS_YEAR,--生产年度
D1 AS END_DATE,--结束日期
N1 AS PREPAR_AREA,--起垄面积
C1 AS IS_HIGH_STAND,--起垄高度是否达到标准
C1.ENUM_NAME AS IS_HIGH_STAND_NAME,--起垄高度是否达到标准_显示名称
C2 AS IS_PROPESS,--是否专业化服务
C2.ENUM_NAME AS IS_PROPESS_NAME,--是否专业化服务_显示名称
C3 AS WORK_EFFECT_EVAL,--实施效果评价
C3.ENUM_NAME AS WORK_EFFECT_EVAL_NAME,--实施效果评价_显示名称
C4 AS SERV_ORG_ID,--服务队ID
C9.STATION_UNIQUE_CD AS ORG_CD,--组织单位
C9.DIVISION_UNIQUE_CD AS AREA_CD,--行政区划,
 A.DATA_STATE 
  FROM PT_DC_STAT_DATA_C A 
      LEFT JOIN PT_IX_ENUM_DATA C1 ON C1.ENUM_CD = A.C1  AND C1.IDX_ID = '8a3c36db4fd1aee7014ff31467e9000a' AND C1.DATA_STATE='1'
      LEFT JOIN PT_IX_ENUM_DATA C3 ON C3.ENUM_CD = A.C3  AND C3.IDX_ID = '8a3c345369b94fd80169b9b9801e00a9' AND C3.DATA_STATE='1'
      LEFT JOIN CM_PM_FRM_FUND C9 ON C9.FRM_FUND_UNIQUE_ID = A.CLT_OBJ_ID AND C9.BIZ_YEAR = A.PT_YEAR AND C9.DATA_STATE = '1'
      LEFT JOIN PT_IX_ENUM_DATA C2 ON C2.ENUM_CD = A.C2  AND C2.IDX_ID = '8a3c36db4fd1aee7014ff31467e9000a' AND C2.DATA_STATE='1' 
 WHERE 1=1 
   AND A.BILL_NO = 'TJHNCD0000000004'
   AND A.CHECK_STATE = '1'   
 ;
 
 
 
 
 --DROP VIEW TSO.V_PT_PREVENT;
CREATE VIEW TSO.V_PT_PREVENT
  AS
 SELECT 
DATA_STORE_BASE_TBL_ID AS PREVENT_ID,--ID
CLT_OBJ_ID AS FARMER_ID,--对应烟农ID
CLT_OBJ_CD AS FARMER_CD,--对应烟农CD
CLT_OBJ_NAME AS FARMER_NAME,--对应烟农名称
FEEDBACK_PSN_ID AS TECHNICIAN_ID,--对应的烟技员ID
FEEDBACK_DATE AS BUSINESS_DATE,--采集日期
PT_YEAR AS BUSINESS_YEAR,--生产年度
N1 AS PREVENT_AREA,--植保面积
C1 AS PREVENT_RESULT,--防治效果评价
C1.ENUM_NAME AS PREVENT_RESULT_NAME,--实施效果评价_显示名称
C2 AS IS_PROPESS,--是否专业化植保
C2.ENUM_NAME AS IS_PROPESS_NAME,--是否专业化植保_显示名称
C3 AS SERV_ORG_ID,--服务队ID
C9.STATION_UNIQUE_CD AS ORG_CD,--组织单位
C9.DIVISION_UNIQUE_CD AS AREA_CD,--行政区划,
B1.PROV,
B1.PROV_NAME,
B1.CITC,
B1.CITC_NAME,
B1.COUC,
B1.COUC_NAME,
B1.STAC,
B1.STAC_NAME,
B1.SSTC,
B1.SSTC_NAME,
B1.SLIN,
B1.SLIN_NAME,
B1.ORG_NAME,
B2.AREA_PROV,
B2.AREA_PROV_NAME,
B2.AREA_CITC,
B2.AREA_CITC_NAME,
B2.AREA_COUC,
B2.AREA_COUC_NAME,
B2.AREA_TOWN,
B2.TOWN_NAME,
B2.AREA_VAGE,
B2.VAGE_NAME,
B2.AREA_GRUP,
B2.GRUP_NAME,
B2.ORG_NAME AS AREA_NAME,
 A.DATA_STATE  
  FROM PT_DC_STAT_DATA_B A 
      LEFT JOIN PT_IX_ENUM_DATA C2 ON C2.ENUM_CD = A.C2 AND C2.IDX_ID = '8a3c36db4fd1aee7014ff31467e9000a' AND C2.DATA_STATE='1'
      LEFT JOIN PT_IX_ENUM_DATA C1 ON C1.ENUM_CD = A.C1 AND C1.IDX_ID = '8a3c345369b94fd80169b9b9801e00a9' AND C1.DATA_STATE='1'
      LEFT JOIN CM_PM_FRM_FUND C9 ON C9.FRM_FUND_UNIQUE_ID = A.CLT_OBJ_ID AND C9.BIZ_YEAR = A.PT_YEAR AND C9.DATA_STATE = '1'
      LEFT JOIN B_ORG B1 ON C9.STATION_UNIQUE_CD = B1.ORG_UNIQUE_CD 
      LEFT JOIN B_DIVISION B2 ON  C9.DIVISION_UNIQUE_CD  = B2.DIVISION_UNIQUE_CD  
 WHERE 1=1 
   AND A.BILL_NO = 'TJHNCD0000000017'
   AND A.CHECK_STATE = '1'   
 ;
 
 
 
 
 --DROP VIEW TSO.V_PT_PREVENT_SY;
CREATE VIEW TSO.V_PT_PREVENT_SY
  AS
 SELECT 
DATA_STORE_BASE_TBL_ID AS PREVENT_SY_ID,--ID
CLT_OBJ_ID AS FARMER_ID,--对应烟农ID
CLT_OBJ_CD AS FARMER_CD,--对应烟农CD
CLT_OBJ_NAME AS FARMER_NAME,--对应烟农名称
FEEDBACK_PSN_ID AS TECHNICIAN_ID,--对应的烟技员ID
FEEDBACK_DATE AS BUSINESS_DATE,--采集日期
PT_YEAR AS BUSINESS_YEAR,--生产年度
D1 AS EMPOLY_DATE,--施药日期
C1 AS PESTIC_NO,--药品编号
C2 AS PESTIC_NAME,--药品名称
N1 AS EMPOLY_QTY,--亩用量（克/毫升）
C1.STATION_UNIQUE_CD AS ORG_CD,--组织单位
C1.DIVISION_UNIQUE_CD AS AREA_CD,--行政区划,
B1.PROV,
B1.PROV_NAME,
B1.CITC,
B1.CITC_NAME,
B1.COUC,
B1.COUC_NAME,
B1.STAC,
B1.STAC_NAME,
B1.SSTC,
B1.SSTC_NAME,
B1.SLIN,
B1.SLIN_NAME,
B1.ORG_NAME,
B2.AREA_PROV,
B2.AREA_PROV_NAME,
B2.AREA_CITC,
B2.AREA_CITC_NAME,
B2.AREA_COUC,
B2.AREA_COUC_NAME,
B2.AREA_TOWN,
B2.TOWN_NAME,
B2.AREA_VAGE,
B2.VAGE_NAME,
B2.AREA_GRUP,
B2.GRUP_NAME,
B2.ORG_NAME AS AREA_NAME,
 A.DATA_STATE  
  FROM PT_DC_STAT_DATA_B A 
      LEFT JOIN CM_PM_FRM_FUND C1 ON C1.FRM_FUND_UNIQUE_ID = A.CLT_OBJ_ID AND C1.BIZ_YEAR = A.PT_YEAR AND C1.DATA_STATE = '1'
      LEFT JOIN B_ORG B1 ON C1.STATION_UNIQUE_CD = B1.ORG_UNIQUE_CD 
      LEFT JOIN B_DIVISION B2 ON  C1.DIVISION_UNIQUE_CD  = B2.DIVISION_UNIQUE_CD  
 WHERE 1=1 
   AND A.BILL_NO = 'TJHNCD0000000019'
   AND A.CHECK_STATE = '1'   
 ;
 
 
 
 --DROP VIEW TSO.V_PT_PUT_FERTILIZ;
CREATE VIEW TSO.V_PT_PUT_FERTILIZ
  AS
 SELECT 
DATA_STORE_BASE_TBL_ID AS PUT_FERTILIZ_D_ID,--ID
CLT_OBJ_ID AS FARMER_ID,--对应烟农ID
CLT_OBJ_CD AS FARMER_CD,--对应烟农CD
CLT_OBJ_NAME AS FARMER_NAME,--对应烟农名称
FEEDBACK_PSN_ID AS TECHNICIAN_ID,--对应的烟技员ID
FEEDBACK_DATE AS BUSINESS_DATE,--采集日期
PT_YEAR AS BUSINESS_YEAR,--生产年度
D1 AS BEGIN_DATE,--开始日期
D2 AS END_DATE,--结束日期
N1 AS FERTILIZ_AREA,--施肥面积
C1 AS IS_MEAL,--是否按套餐施肥
C1.ENUM_NAME AS IS_MEAL_NAME,--是否按套餐施肥_显示名称
C2 AS FERTILIZ_STAND,--施肥标准
C2.ENUM_NAME AS FERTILIZ_STAND_NAME,--施肥标准_显示名称
C9.STATION_UNIQUE_CD AS ORG_CD,--组织单位
C9.DIVISION_UNIQUE_CD AS AREA_CD,--行政区划,
B1.PROV,
B1.PROV_NAME,
B1.CITC,
B1.CITC_NAME,
B1.COUC,
B1.COUC_NAME,
B1.STAC,
B1.STAC_NAME,
B1.SSTC,
B1.SSTC_NAME,
B1.SLIN,
B1.SLIN_NAME,
B1.ORG_NAME,
B2.AREA_PROV,
B2.AREA_PROV_NAME,
B2.AREA_CITC,
B2.AREA_CITC_NAME,
B2.AREA_COUC,
B2.AREA_COUC_NAME,
B2.AREA_TOWN,
B2.TOWN_NAME,
B2.AREA_VAGE,
B2.VAGE_NAME,
B2.AREA_GRUP,
B2.GRUP_NAME,
B2.ORG_NAME AS AREA_NAME,
 A.DATA_STATE  
  FROM PT_DC_STAT_DATA_B A 
      LEFT JOIN PT_IX_ENUM_DATA C1 ON C1.ENUM_CD = A.C1 AND C1.IDX_ID = '8a3c36db4fd1aee7014ff31467e9000a' AND C1.DATA_STATE='1'
      LEFT JOIN CM_PM_FRM_FUND C9 ON C9.FRM_FUND_UNIQUE_ID = A.CLT_OBJ_ID AND C9.BIZ_YEAR = A.PT_YEAR AND C9.DATA_STATE = '1'
      LEFT JOIN PT_IX_ENUM_DATA C2 ON C2.ENUM_CD = A.C2 AND C2.IDX_ID = '8a3c34536a8b0c37016a8c9baf000001' AND C2.DATA_STATE='1'
      LEFT JOIN B_ORG B1 ON C9.STATION_UNIQUE_CD = B1.ORG_UNIQUE_CD 
      LEFT JOIN B_DIVISION B2 ON  C9.DIVISION_UNIQUE_CD  = B2.DIVISION_UNIQUE_CD  
 WHERE 1=1 
   AND A.BILL_NO = 'TJHNCD0000000005'
   AND A.CHECK_STATE = '1'   
 ;
 
 
 
 
 --DROP VIEW TSO.V_PT_RECOVERY;
CREATE VIEW TSO.V_PT_RECOVERY
  AS
 SELECT 
DATA_STORE_BASE_TBL_ID AS RECOVERY_ID,--ID
CLT_OBJ_ID AS FARMER_ID,--对应烟农ID
CLT_OBJ_CD AS FARMER_CD,--对应烟农CD
CLT_OBJ_NAME AS FARMER_NAME,--对应烟农名称
FEEDBACK_PSN_ID AS TECHNICIAN_ID,--对应的烟技员ID
FEEDBACK_DATE AS BUSINESS_DATE,--采集日期
PT_YEAR AS BUSINESS_YEAR,--生产年度
N1 AS RECOVERY_AREA,--采收面积
C1 AS IS_CERT_RECOVERY,--是否凭证采收
C1.ENUM_NAME AS IS_CERT_RECOVERY_NAME,--是否凭证采收_显示名称
C2 AS RIPE_GRADE,--采收烟叶成熟度
C2.ENUM_NAME AS RIPE_GRADE_NAME,--采收烟叶成熟度_显示名称
C9.STATION_UNIQUE_CD AS ORG_CD,--组织单位
C9.DIVISION_UNIQUE_CD AS AREA_CD,--行政区划,
B1.PROV,
B1.PROV_NAME,
B1.CITC,
B1.CITC_NAME,
B1.COUC,
B1.COUC_NAME,
B1.STAC,
B1.STAC_NAME,
B1.SSTC,
B1.SSTC_NAME,
B1.SLIN,
B1.SLIN_NAME,
B1.ORG_NAME,
B2.AREA_PROV,
B2.AREA_PROV_NAME,
B2.AREA_CITC,
B2.AREA_CITC_NAME,
B2.AREA_COUC,
B2.AREA_COUC_NAME,
B2.AREA_TOWN,
B2.TOWN_NAME,
B2.AREA_VAGE,
B2.VAGE_NAME,
B2.AREA_GRUP,
B2.GRUP_NAME,
B2.ORG_NAME AS AREA_NAME,
 A.DATA_STATE  
  FROM PT_DC_STAT_DATA_B A 
      LEFT JOIN PT_IX_ENUM_DATA C2 ON C2.ENUM_CD = A.C2 AND C2.IDX_ID = '8a3c345369b94fd80169b9b9801e00a9' AND C2.DATA_STATE='1'
      LEFT JOIN PT_IX_ENUM_DATA C1 ON C1.ENUM_CD = A.C1 AND C1.IDX_ID = '8a3c36db4fd1aee7014ff31467e9000a' AND C1.DATA_STATE='1'
      LEFT JOIN CM_PM_FRM_FUND C9 ON C9.FRM_FUND_UNIQUE_ID = A.CLT_OBJ_ID AND C9.BIZ_YEAR = A.PT_YEAR AND C9.DATA_STATE = '1'
      LEFT JOIN B_ORG B1 ON C9.STATION_UNIQUE_CD = B1.ORG_UNIQUE_CD 
      LEFT JOIN B_DIVISION B2 ON  C9.DIVISION_UNIQUE_CD  = B2.DIVISION_UNIQUE_CD  
 WHERE 1=1 
   AND A.BILL_NO = 'TJHNCD0000000020'
   AND A.CHECK_STATE = '1'   
 ;
 
 
 
 
 --DROP VIEW TSO.V_PT_SMALL_PTSX;
CREATE VIEW TSO.V_PT_SMALL_PTSX
  AS
 SELECT 
DATA_STORE_BASE_TBL_ID AS SMALL_PTSX_ID,--ID
CLT_OBJ_ID AS FARMER_ID,--对应烟农ID
CLT_OBJ_CD AS FARMER_CD,--对应烟农CD
CLT_OBJ_NAME AS FARMER_NAME,--对应烟农名称
FEEDBACK_PSN_ID AS TECHNICIAN_ID,--对应的烟技员ID
FEEDBACK_DATE AS BUSINESS_DATE,--采集日期
PT_YEAR AS BUSINESS_YEAR,--生产年度
D1 AS BEGIN_DATE,--开始日期
D2 AS END_DATE,--结束日期
N1 AS PTSX_AREA,--培土面积
C1 AS IS_HIGH_STAND,--垄高高度是否达到标准
C1.ENUM_NAME AS IS_HIGH_STAND_NAME,--垄高高度是否达到标准_显示名称
C2 AS WORK_EFFECT_EVAL,--实施效果评价
C2.ENUM_NAME AS WORK_EFFECT_EVAL_NAME,--实施效果评价_显示名称
C9.STATION_UNIQUE_CD AS ORG_CD,--组织单位
C9.DIVISION_UNIQUE_CD AS AREA_CD,--行政区划,
B1.PROV,
B1.PROV_NAME,
B1.CITC,
B1.CITC_NAME,
B1.COUC,
B1.COUC_NAME,
B1.STAC,
B1.STAC_NAME,
B1.SSTC,
B1.SSTC_NAME,
B1.SLIN,
B1.SLIN_NAME,
B1.ORG_NAME,
B2.AREA_PROV,
B2.AREA_PROV_NAME,
B2.AREA_CITC,
B2.AREA_CITC_NAME,
B2.AREA_COUC,
B2.AREA_COUC_NAME,
B2.AREA_TOWN,
B2.TOWN_NAME,
B2.AREA_VAGE,
B2.VAGE_NAME,
B2.AREA_GRUP,
B2.GRUP_NAME,
B2.ORG_NAME AS AREA_NAME,
 A.DATA_STATE  
  FROM PT_DC_STAT_DATA_F A 
      LEFT JOIN PT_IX_ENUM_DATA C2 ON C2.ENUM_CD = A.C2 AND C2.IDX_ID = '8a3c345369b94fd80169b9b9801e00a9' AND C2.DATA_STATE='1'
      LEFT JOIN PT_IX_ENUM_DATA C1 ON C1.ENUM_CD = A.C1 AND C1.IDX_ID = '8a3c36db4fd1aee7014ff31467e9000a' AND C1.DATA_STATE='1'
      LEFT JOIN CM_PM_FRM_FUND C9 ON C9.FRM_FUND_UNIQUE_ID = A.CLT_OBJ_ID AND C9.BIZ_YEAR = A.PT_YEAR AND C9.DATA_STATE = '1'
      LEFT JOIN B_ORG B1 ON C9.STATION_UNIQUE_CD = B1.ORG_UNIQUE_CD 
      LEFT JOIN B_DIVISION B2 ON  C9.DIVISION_UNIQUE_CD  = B2.DIVISION_UNIQUE_CD  
 WHERE 1=1 
   AND A.BILL_NO = 'TJHNCD0000000011'
   AND A.CHECK_STATE = '1'   
 ;
 
 
 
 
 
 --DROP VIEW TSO.V_PT_TRANSPLANT_FM_D;
CREATE VIEW TSO.V_PT_TRANSPLANT_FM_D
  AS
 SELECT 
DATA_STORE_BASE_TBL_ID AS TRANSPLANT_FM_D_ID,--ID
CLT_OBJ_ID AS FARMER_ID,--对应烟农ID
CLT_OBJ_CD AS FARMER_CD,--对应烟农CD
CLT_OBJ_NAME AS FARMER_NAME,--对应烟农名称
FEEDBACK_DATE AS BUSINESS_DATE,--采集日期
PT_YEAR AS BUSINESS_YEAR,--生产年度
D1 AS BEGIN_DATE,--开始日期
D2 AS END_DATE,--结束日期
N1 AS TRANSPLANT_AREA,--移栽面积
C1 AS LINE_DISTANCE,--行距
C1.ENUM_NAME AS LINE_DISTANCE_NAME,--行距_显示名称
C2 AS ONE_DISTANCE,--株距
C2.ENUM_NAME AS ONE_DISTANCE_NAME,--株距_显示名称
C3 AS WORK_EFFECT_EVAL,--实施效果评价
C3.ENUM_NAME AS WORK_EFFECT_EVAL_NAME,--实施效果评价_显示名称
C9.STATION_UNIQUE_CD AS ORG_CD,--组织单位
C9.DIVISION_UNIQUE_CD AS AREA_CD,--行政区划,
 A.DATA_STATE 
  FROM PT_DC_STAT_DATA_B A 
      LEFT JOIN CM_PM_FRM_FUND C9 ON C9.FRM_FUND_UNIQUE_ID = A.CLT_OBJ_ID AND C9.BIZ_YEAR = A.PT_YEAR AND C9.DATA_STATE = '1'
      LEFT JOIN PT_IX_ENUM_DATA C3 ON C3.ENUM_CD = A.C3  AND C3.IDX_ID = '8a3c345369b94fd80169b9b9801e00a9' AND C3.DATA_STATE='1'
      LEFT JOIN PT_IX_ENUM_DATA C2 ON C2.ENUM_CD = A.C2  AND C2.IDX_ID = '8a3c34536a68f3fa016a860323fc00ae' AND C2.DATA_STATE='1'
      LEFT JOIN PT_IX_ENUM_DATA C1 ON C1.ENUM_CD = A.C1  AND C1.IDX_ID = '8a3c34536a68f3fa016a860017aa00a9' AND C1.DATA_STATE='1' 
 WHERE 1=1 
   AND A.BILL_NO = 'TJHNCD0000000002'
   AND A.CHECK_STATE = '1'   
 ;
 
