--PT_DC_STAT_DATA_SUM_Z
DROP TABLE TSO.PT_DC_STAT_DATA_SUM_Z_COPY;
CREATE TABLE TSO.PT_DC_STAT_DATA_SUM_Z_COPY LIKE TSO.PT_DC_STAT_DATA_SUM_Z;
INSERT INTO TSO.PT_DC_STAT_DATA_SUM_Z_COPY SELECT * FROM TSO.PT_DC_STAT_DATA_SUM_Z;

DROP TABLE TSO.PT_DC_STAT_DATA_SUM_Z;
CREATE TABLE
    TSO.PT_DC_STAT_DATA_SUM_Z
    (
        DATA_STORE_STAT_TBL_ID VARCHAR(32) PRIMARY KEY NOT NULL,
        BILL_NO VARCHAR(32),
        CLT_FREQ_EK VARCHAR(16),
        STAT_PERIOD DECIMAL(12,2) DEFAULT 0,
        STAT_DATE TIMESTAMP,
        STAT_OBJ_ID VARCHAR(32),
        STAT_OBJ_CD VARCHAR(32),
        STAT_OBJ_NAME VARCHAR(64),
        STAT_OBJ_TYPE_EK VARCHAR(16),
        SITE_ORG_UNIQUE_CD VARCHAR(20),
        STATION_ORG_UNIQUE_CD VARCHAR(20),
        COUC_ORG_UNIQUE_CD VARCHAR(20),
        CITY_ORG_UNIQUE_CD VARCHAR(20),
        PROV_ORG_UNIQUE_CD VARCHAR(20),
        COUNTRY_ORG_UNIQUE_CD VARCHAR(20),
        T_DIVISION_UNIQUE_CD VARCHAR(16),
        X_DIVISION_UNIQUE_CD VARCHAR(16),
        C_DIVISION_UNIQUE_CD VARCHAR(16),
        P_DIVISION_UNIQUE_CD VARCHAR(16),
        LEAF_VARIETY_CD VARCHAR(32),
        LEAF_TYPE_CD VARCHAR(32),
        LEAF_POSITION_CD VARCHAR(32),
        FRM_CD VARCHAR(32),
        SERV_ORG_ID VARCHAR(32),
        GROW_SITE_CD VARCHAR(32),
        BAKE_HOUSE_CD VARCHAR(32),
        PT_YEAR DECIMAL(4,0),
        CLT_OBJ_NUM DECIMAL(12,0) DEFAULT 0,
        IS_STAT_FLAG CHARACTER(1) DEFAULT '0',
        IS_RETURN_FLAG CHARACTER(1) DEFAULT '0',
        CONFIRM_STATE CHARACTER(1),
        ORG_UNIQUE_CD VARCHAR(20),
        SEND_STATE CHARACTER(1) DEFAULT '0',
        MODIFY_TIME TIMESTAMP,
        DATA_STATE CHARACTER(1) DEFAULT '1',
        LAST_TIME TIMESTAMP,
        N1 DECIMAL(20,5),
        N2 DECIMAL(20,5),
        N3 DECIMAL(20,5),
        N4 DECIMAL(20,5),
        N5 DECIMAL(20,5),
        N6 DECIMAL(20,5),
        N7 DECIMAL(20,5),
        N8 DECIMAL(20,5),
        N9 DECIMAL(20,5),
        N10 DECIMAL(20,5),
        N11 DECIMAL(20,5),
        N12 DECIMAL(20,5),
        N13 DECIMAL(20,5),
        N14 DECIMAL(20,5),
        N15 DECIMAL(20,5),
        N16 DECIMAL(20,5),
        N17 DECIMAL(20,5),
        N18 DECIMAL(20,5),
        N19 DECIMAL(20,5),
        N20 DECIMAL(20,5),
        N21 DECIMAL(20,5),
        N22 DECIMAL(20,5),
        N23 DECIMAL(20,5),
        N24 DECIMAL(20,5),
        N25 DECIMAL(20,5),
        N26 DECIMAL(20,5),
        N27 DECIMAL(20,5),
        N31 DECIMAL(20,5),
        N32 DECIMAL(20,5),
        N33 DECIMAL(20,5),
        N34 DECIMAL(20,5),
        N35 DECIMAL(20,5),
        N36 DECIMAL(20,5),
        N37 DECIMAL(20,5),
        N38 DECIMAL(20,5),
        N39 DECIMAL(20,5),
        N40 DECIMAL(20,5),
        N41 DECIMAL(20,5),
        N42 DECIMAL(20,5),
        N43 DECIMAL(20,5),
        N44 DECIMAL(20,5),
        N45 DECIMAL(20,5),
        N46 DECIMAL(20,5),
        N47 DECIMAL(20,5),
        N48 DECIMAL(20,5),
        N49 DECIMAL(20,5),
        N50 DECIMAL(20,5),
        N28 DECIMAL(20,5),
        N29 DECIMAL(20,5),
        N30 DECIMAL(20,5),
        C1 VARCHAR(255),
        C2 VARCHAR(255),
        C3 VARCHAR(255),
        C4 VARCHAR(255),
        C5 VARCHAR(255),
        C6 VARCHAR(255),
        C7 VARCHAR(255),
        C8 VARCHAR(255),
        C9 VARCHAR(255),
        C10 VARCHAR(255),
        C11 VARCHAR(255),
        C12 VARCHAR(255),
        C13 VARCHAR(255),
        C14 VARCHAR(255),
        C15 VARCHAR(255),
        C16 VARCHAR(255),
        C17 VARCHAR(255),
        C18 VARCHAR(255),
        C19 VARCHAR(255),
        C20 VARCHAR(255),
        D1 TIMESTAMP,
        D2 TIMESTAMP,
        D3 TIMESTAMP,
        D4 TIMESTAMP,
        D5 TIMESTAMP,
        D6 TIMESTAMP,
        D7 TIMESTAMP,
        D8 TIMESTAMP,
        D9 TIMESTAMP,
        D10 TIMESTAMP,
        IS_COPY_FLAG CHARACTER(1) DEFAULT '0',
        IS_UPLOAD_FLAG CHARACTER(1) DEFAULT '0',
        IS_FREEZE_FLAG CHARACTER(1) DEFAULT '0',
        N51 DECIMAL(20,5),
        N52 DECIMAL(20,5),
        N53 DECIMAL(20,5),
        N54 DECIMAL(20,5),
        N55 DECIMAL(20,5),
        N56 DECIMAL(20,5),
        N57 DECIMAL(20,5),
        N58 DECIMAL(20,5),
        N59 DECIMAL(20,5),
        N60 DECIMAL(20,5),
        V_DIVISION_UNIQUE_CD VARCHAR(16),
        N61 DECIMAL(20,5),
        N62 DECIMAL(20,5),
        N63 DECIMAL(20,5),
        N64 DECIMAL(20,5),
        N65 DECIMAL(20,5),
        N66 DECIMAL(20,5),
        N67 DECIMAL(20,5),
        N68 DECIMAL(20,5),
        N69 DECIMAL(20,5),
        N70 DECIMAL(20,5),
        IS_CHECK_RELEASE_FLAG CHARACTER(1) DEFAULT '0',
        D11 TIMESTAMP,
        D12 TIMESTAMP,
        D13 TIMESTAMP,
        D14 TIMESTAMP,
        D15 TIMESTAMP,
        D16 TIMESTAMP,
        C21 VARCHAR(32),
        C22 VARCHAR(32),
        C23 VARCHAR(32),
        C24 VARCHAR(32),
        C25 VARCHAR(32),
        C26 VARCHAR(32),
        C27 VARCHAR(32),
        C28 VARCHAR(32),
        C29 VARCHAR(32),
        C30 VARCHAR(32),
        C31 VARCHAR(32),
        C32 VARCHAR(32),
        C33 VARCHAR(32),
        C34 VARCHAR(32),
        C35 VARCHAR(32),
        C36 VARCHAR(32),
        C37 VARCHAR(32),
        C38 VARCHAR(32),
        C39 VARCHAR(32),
        C40 VARCHAR(32),
        C41 VARCHAR(32),
        C42 VARCHAR(32),
        C43 VARCHAR(32),
        C44 VARCHAR(32),
        C45 VARCHAR(32),
        C46 VARCHAR(32),
        C47 VARCHAR(32),
		C48 VARCHAR(32),
        C49 VARCHAR(32),
        C50 VARCHAR(32),
        C51 VARCHAR(32),
        C52 VARCHAR(32),
        C53 VARCHAR(32),
        C54 VARCHAR(32),
        C55 VARCHAR(32),
        C56 VARCHAR(32),
        C57 VARCHAR(32),
        C58 VARCHAR(32),
        C59 VARCHAR(32),
        C60 VARCHAR(32),
        C61 VARCHAR(32),
        C62 VARCHAR(32),
        C63 VARCHAR(32),
        C64 VARCHAR(32),
        C65 VARCHAR(32),
        C66 VARCHAR(32),
        C67 VARCHAR(32),
        C68 VARCHAR(32),
        C69 VARCHAR(32),
        C70 VARCHAR(32),
        C71 VARCHAR(32),
        C72 VARCHAR(32),
        C73 VARCHAR(32),
        C74 VARCHAR(32),
        C75 VARCHAR(32)
    )in TS_TSO_32K;
	
COMMENT ON TABLE PT_DC_STAT_DATA_SUM_Z
IS
    '生产统计数据汇总存储表Z';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.DATA_STORE_STAT_TBL_ID
IS
    '主键';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.BILL_NO
IS
    '单据编号';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.CLT_FREQ_EK
IS
    '填报频率类型';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.STAT_PERIOD
IS
    '汇总期数';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.STAT_DATE
IS
    '汇总日期';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.STAT_OBJ_ID
IS
    '汇总对象ID';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.STAT_OBJ_CD
IS
    '汇总对象CD';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.STAT_OBJ_NAME
IS
    '汇总对象名称';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.STAT_OBJ_TYPE_EK
IS
    '汇总对象类型';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.SITE_ORG_UNIQUE_CD
IS
    '烟点单位CD';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.STATION_ORG_UNIQUE_CD
IS
    '烟站单位CD';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.COUC_ORG_UNIQUE_CD
IS
    '县公司单位CD';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.CITY_ORG_UNIQUE_CD
IS
    '市公司单位CD';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.PROV_ORG_UNIQUE_CD
IS
    '省公司单位CD';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.COUNTRY_ORG_UNIQUE_CD
IS
    '国家局单位CD';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.T_DIVISION_UNIQUE_CD
IS
    '所在乡镇CD';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.X_DIVISION_UNIQUE_CD
IS
    '所在县CD';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.C_DIVISION_UNIQUE_CD
IS
    '所在市CD';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.P_DIVISION_UNIQUE_CD
IS
    '所在省CD';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.LEAF_VARIETY_CD
IS
    '烟叶品种代码';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.LEAF_TYPE_CD
IS
    '烟叶类型代码';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.LEAF_POSITION_CD
IS
    '烟叶部位代码';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.FRM_CD
IS
    '种植主体编码';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.SERV_ORG_ID
IS
    '服务组织ID';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.PT_YEAR
IS
    '生产年度';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.CLT_OBJ_NUM
IS
    '采集对象个数';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.IS_STAT_FLAG
IS
    '已统计标志';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.CONFIRM_STATE
IS
    '确认状态';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.ORG_UNIQUE_CD
IS
    '组织机构唯一代码';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.SEND_STATE
IS
    '传输状态';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.MODIFY_TIME
IS
    '修改时间';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.DATA_STATE
IS
    '数据状态';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.LAST_TIME
IS
    '最后入库时间';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N1
IS
    '数值型字段1';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N2
IS
    '数值型字段2';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N3
IS
    '数值型字段3';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N4
IS
    '数值型字段4';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N5
IS
    '数值型字段5';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N6
IS
    '数值型字段6';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N7
IS
    '数值型字段7';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N8
IS
    '数值型字段8';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N9
IS
    '数值型字段9';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N10
IS
    '数值型字段10';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N11
IS
    '数值型字段11';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N12
IS
    '数值型字段12';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N13
IS
    '数值型字段13';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N14
IS
    '数值型字段14';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N15
IS
    '数值型字段15';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N16
IS
    '数值型字段16';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N17
IS
    '数值型字段17';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N18
IS
    '数值型字段18';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N19
IS
    '数值型字段19';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N20
IS
    '数值型字段20';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N21
IS
    '数值型字段21';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N22
IS
    '数值型字段22';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N23
IS
    '数值型字段23';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N24
IS
    '数值型字段24';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N25
IS
    '数值型字段25';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N26
IS
    '数值型字段26';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N27
IS
    '数值型字段27';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N31
IS
    '数值型字段31';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N32
IS
    '数值型字段32';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N33
IS
    '数值型字段33';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N34
IS
    '数值型字段34';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N35
IS
    '数值型字段35';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N36
IS
    '数值型字段36';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N37
IS
    '数值型字段37';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N38
IS
    '数值型字段38';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N39
IS
    '数值型字段39';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N40
IS
    '数值型字段40';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N41
IS
    '数值型字段41';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N42
IS
    '数值型字段42';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N43
IS
    '数值型字段43';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N44
IS
    '数值型字段44';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N45
IS
    '数值型字段45';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N46
IS
    '数值型字段46';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N47
IS
    '数值型字段47';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N48
IS
    '数值型字段48';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N49
IS
    '数值型字段49';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N50
IS
    '数值型字段50';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N28
IS
    '数值型字段28';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N29
IS
    '数值型字段29';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.N30
IS
    '数值型字段30';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.C1
IS
    '长字符型字段1';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.C2
IS
    '长字符型字段2';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.C3
IS
    '长字符型字段3';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.C4
IS
    '长字符型字段4';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.C5
IS
    '长字符型字段5';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.C6
IS
    '长字符型字段6';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.C7
IS
    '长字符型字段7';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.C8
IS
    '长字符型字段8';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.C9
IS
    '长字符型字段9';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.C10
IS
    '长字符型字段10';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.D1
IS
    '日期型字段1';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.D2
IS
    '日期型字段2';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.D3
IS
    '日期型字段3';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.D4
IS
    '日期型字段4';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.D5
IS
    '日期型字段5';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.D6
IS
    '日期型字段6';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.D7
IS
    '日期型字段7';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.D8
IS
    '日期型字段8';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.D9
IS
    '日期型字段9';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.D10
IS
    '日期型字段10';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.IS_COPY_FLAG
IS
    '是否副本';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.IS_FREEZE_FLAG
IS
    '是否冻结';
COMMENT ON COLUMN PT_DC_STAT_DATA_SUM_Z.IS_CHECK_RELEASE_FLAG
IS
    '检查发布标志';
	
	INSERT
INTO
    TSO.PT_DC_STAT_DATA_SUM_Z
    (
        DATA_STORE_STAT_TBL_ID,
        BILL_NO,
        CLT_FREQ_EK,
        STAT_PERIOD,
        STAT_DATE,
        STAT_OBJ_ID,
        STAT_OBJ_CD,
        STAT_OBJ_NAME,
        STAT_OBJ_TYPE_EK,
        SITE_ORG_UNIQUE_CD,
        STATION_ORG_UNIQUE_CD,
        COUC_ORG_UNIQUE_CD,
        CITY_ORG_UNIQUE_CD,
        PROV_ORG_UNIQUE_CD,
        COUNTRY_ORG_UNIQUE_CD,
        T_DIVISION_UNIQUE_CD,
        X_DIVISION_UNIQUE_CD,
        C_DIVISION_UNIQUE_CD,
        P_DIVISION_UNIQUE_CD,
        LEAF_VARIETY_CD,
        LEAF_TYPE_CD,
        LEAF_POSITION_CD,
        FRM_CD,
        SERV_ORG_ID,
        GROW_SITE_CD,
        BAKE_HOUSE_CD,
        PT_YEAR,
        CLT_OBJ_NUM,
        IS_STAT_FLAG,
        IS_RETURN_FLAG,
        CONFIRM_STATE,
        ORG_UNIQUE_CD,
        SEND_STATE,
        MODIFY_TIME,
        DATA_STATE,
        LAST_TIME,
        N1,
        N2,
        N3,
        N4,
        N5,
        N6,
        N7,
        N8,
        N9,
        N10,
        N11,
        N12,
        N13,
        N14,
        N15,
        N16,
        N17,
        N18,
        N19,
        N20,
        N21,
        N22,
        N23,
        N24,
        N25,
        N26,
        N27,
        N31,
        N32,
        N33,
        N34,
        N35,
        N36,
        N37,
        N38,
        N39,
        N40,
        N41,
        N42,
        N43,
        N44,
        N45,
        N46,
        N47,
        N48,
        N49,
        N50,
        N28,
        N29,
        N30,
        C1,
        C2,
        C3,
        C4,
        C5,
        C6,
        C7,
        C8,
        C9,
        C10,
        C11,
        C12,
        C13,
        C14,
        C15,
        C16,
        C17,
        C18,
        C19,
        C20,
        D1,
        D2,
        D3,
        D4,
        D5,
        D6,
        D7,
        D8,
        D9,
        D10,
        IS_COPY_FLAG,
        IS_UPLOAD_FLAG,
        IS_FREEZE_FLAG,
        N51,
        N52,
        N53,
        N54,
        N55,
        N56,
        N57,
        N58,
        N59,
        N60,
        V_DIVISION_UNIQUE_CD,
        N61,
        N62,
        N63,
        N64,
        N65,
        N66,
        N67,
        N68,
        N69,
        N70,
        IS_CHECK_RELEASE_FLAG,
        D11,
        D12,
        D13,
        D14,
        D15,
        D16
    )
SELECT
    DATA_STORE_STAT_TBL_ID,
    BILL_NO,
    CLT_FREQ_EK,
    STAT_PERIOD,
    STAT_DATE,
    STAT_OBJ_ID,
    STAT_OBJ_CD,
    STAT_OBJ_NAME,
    STAT_OBJ_TYPE_EK,
    SITE_ORG_UNIQUE_CD,
    STATION_ORG_UNIQUE_CD,
    COUC_ORG_UNIQUE_CD,
    CITY_ORG_UNIQUE_CD,
    PROV_ORG_UNIQUE_CD,
    COUNTRY_ORG_UNIQUE_CD,
    T_DIVISION_UNIQUE_CD,
    X_DIVISION_UNIQUE_CD,
    C_DIVISION_UNIQUE_CD,
    P_DIVISION_UNIQUE_CD,
    LEAF_VARIETY_CD,
    LEAF_TYPE_CD,
    LEAF_POSITION_CD,
    FRM_CD,
    SERV_ORG_ID,
    GROW_SITE_CD,
    BAKE_HOUSE_CD,
    PT_YEAR,
    CLT_OBJ_NUM,
    IS_STAT_FLAG,
    IS_RETURN_FLAG,
    CONFIRM_STATE,
    ORG_UNIQUE_CD,
    SEND_STATE,
    MODIFY_TIME,
    DATA_STATE,
    LAST_TIME,
    N1,
    N2,
    N3,
    N4,
    N5,
    N6,
    N7,
    N8,
    N9,
    N10,
    N11,
    N12,
    N13,
    N14,
    N15,
    N16,
    N17,
    N18,
    N19,
    N20,
    N21,
    N22,
    N23,
    N24,
    N25,
    N26,
    N27,
    N31,
    N32,
    N33,
    N34,
    N35,
    N36,
    N37,
    N38,
    N39,
    N40,
    N41,
    N42,
    N43,
    N44,
    N45,
    N46,
    N47,
    N48,
    N49,
    N50,
    N28,
    N29,
    N30,
    C1,
    C2,
    C3,
    C4,
    C5,
    C6,
    C7,
    C8,
    C9,
    C10,
    C11,
    C12,
    C13,
    C14,
    C15,
    C16,
    C17,
    C18,
    C19,
    C20,
    D1,
    D2,
    D3,
    D4,
    D5,
    D6,
    D7,
    D8,
    D9,
    D10,
    IS_COPY_FLAG,
    IS_UPLOAD_FLAG,
    IS_FREEZE_FLAG,
    N51,
    N52,
    N53,
    N54,
    N55,
    N56,
    N57,
    N58,
    N59,
    N60,
    V_DIVISION_UNIQUE_CD,
    N61,
    N62,
    N63,
    N64,
    N65,
    N66,
    N67,
    N68,
    N69,
    N70,
    IS_CHECK_RELEASE_FLAG,
    D11,
    D12,
    D13,
    D14,
    D15,
    D16
FROM
    PT_DC_STAT_DATA_SUM_Z_COPY;
	