--DROP TABLE R_TMP_FARMER_STAR;
--DROP NICKNAME "DCCELL"."R_TMP_FARMER_STAR"
CREATE TABLE
    DCCELL.R_TMP_FARMER_STAR
    (
        FRM_FUND_UNIQUE_ID VARCHAR(32)  PRIMARY KEY NOT NULL,
        FRM_CD VARCHAR(32),
        FRM_NAME VARCHAR(64),
        FRM_AGE DECIMAL(4,0),
        FRM_EDU VARCHAR(32),
        BUSINESS_YEAR DECIMAL(4,0),
        PLNT_START_YEAR DECIMAL(4,0) DEFAULT 0,
        PLNT_YEAR DECIMAL(24,6) DEFAULT 0,
        CNTRCT_PLNT_AREA DECIMAL(24,6) DEFAULT 0,
        CNTRCT_PLNT_AREA_THREE_YEAR DECIMAL(24,6) DEFAULT 0,
        BUY_CNTRCT_RATE DECIMAL(24,6) DEFAULT 0,
        BUY_CNTRCT_RATE_TWO_YEAR DECIMAL(24,6) DEFAULT 0,
        UP_RATE DECIMAL(24,6) DEFAULT 0,
        UP_COUC_AVG_SUB DECIMAL(24,6) DEFAULT 0,
        MU_AVG_REVENUE DECIMAL(24,6) DEFAULT 0,
        MU_AVG_REVENUE_COUC_AVG_SUB DECIMAL(24,6) DEFAULT 0,
        MIDUP_RATE DECIMAL(24,6) DEFAULT 0,
        UPMID_RATE DECIMAL(24,6) DEFAULT 0,
        MID_RATE DECIMAL(24,6) DEFAULT 0,
        SALE_QUANTITY DECIMAL(24,6) DEFAULT 0,
        SALE_AVG DECIMAL(24,6) DEFAULT 0,
        SALE_AVG_STAT_SUB DECIMAL(24,6) DEFAULT 0,
        CNTRCT_WGHT DECIMAL(24,6) DEFAULT 0,
        PRECHECK_WGHT DECIMAL(24,6) DEFAULT 0,
        BUY_WGHT DECIMAL(24,6) DEFAULT 0,
        UPMID_BUY_WGHT DECIMAL(24,6) DEFAULT 0,
        BUY_PRECHECK_RATE DECIMAL(24,6) DEFAULT 0,
        PER_MU_YIELD DECIMAL(24,6) DEFAULT 0,
        FOURC_RATE DECIMAL(24,6) DEFAULT 0,
        FOURC_COUC_AVG_SUB DECIMAL(24,6) DEFAULT 0,
        DAN_AVG_PRICE DECIMAL(24,6) DEFAULT 0,
        DAN_AVG_PRICE_COUC_AVG_SUB DECIMAL(24,6) DEFAULT 0,
        PROV VARCHAR(32) DEFAULT '0',
        PROV_NAME VARCHAR(128),
        CITC VARCHAR(32) DEFAULT '0',
        CITC_NAME VARCHAR(128),
        COUC VARCHAR(32) DEFAULT '0',
        COUC_NAME VARCHAR(128),
        STAC VARCHAR(32) DEFAULT '0',
        STAC_NAME VARCHAR(128),
        SSTC VARCHAR(32) DEFAULT '0',
        SSTC_NAME VARCHAR(128),
        AREA_PROV VARCHAR(32) DEFAULT '0',
        AREA_PROV_NAME VARCHAR(128),
        AREA_CITC VARCHAR(32) DEFAULT '0',
        AREA_CITC_NAME VARCHAR(128),
        AREA_COUC VARCHAR(32) DEFAULT '0',
        AREA_COUC_NAME VARCHAR(128),
        AREA_TOWN VARCHAR(32) DEFAULT '0',
        TOWN_NAME VARCHAR(128),
        AREA_VAGE VARCHAR(32) DEFAULT '0',
        VAGE_NAME VARCHAR(128),
        AREA_GRUP VARCHAR(32) DEFAULT '0',
        GRUP_NAME VARCHAR(128)
    )IN DCCELL_SPACE_32K INDEX IN INDEX_SPACE;
    
COMMENT ON COLUMN R_TMP_FARMER_STAR.FRM_CD IS '烟农编号';
COMMENT ON COLUMN R_TMP_FARMER_STAR.FRM_NAME IS  '烟农名称';
COMMENT ON COLUMN R_TMP_FARMER_STAR.FRM_AGE IS '烟农年龄';
COMMENT ON COLUMN R_TMP_FARMER_STAR.FRM_EDU IS '烟农学历';
COMMENT ON COLUMN R_TMP_FARMER_STAR.BUSINESS_YEAR IS '业务年度';
COMMENT ON COLUMN R_TMP_FARMER_STAR.PLNT_START_YEAR IS  '开始种植年限';
COMMENT ON COLUMN R_TMP_FARMER_STAR.PLNT_YEAR IS '连续种烟年限';
COMMENT ON COLUMN R_TMP_FARMER_STAR.CNTRCT_PLNT_AREA IS '种植面积/种植规模';
COMMENT ON COLUMN R_TMP_FARMER_STAR.CNTRCT_PLNT_AREA_THREE_YEAR IS  '种植面积/种植规模(最近三年)';
COMMENT ON COLUMN R_TMP_FARMER_STAR.BUY_CNTRCT_RATE IS '合同履约率/合同完成比例';
COMMENT ON COLUMN R_TMP_FARMER_STAR.BUY_CNTRCT_RATE_TWO_YEAR IS  '合同履约率/合同完成比例(最近两年)';
COMMENT ON COLUMN R_TMP_FARMER_STAR.UP_RATE IS '上等烟比例(不区分品种)';
COMMENT ON COLUMN R_TMP_FARMER_STAR.UP_COUC_AVG_SUB IS '上等烟比例与县平均差值(不区分品种)';
COMMENT ON COLUMN R_TMP_FARMER_STAR.MU_AVG_REVENUE IS '亩均售烟收入/亩平均收入';
COMMENT ON COLUMN R_TMP_FARMER_STAR.MU_AVG_REVENUE_COUC_AVG_SUB IS '亩均售烟收入(亩平均收入)与县平均差值';
COMMENT ON COLUMN R_TMP_FARMER_STAR.MIDUP_RATE IS '中部上等烟比例';
COMMENT ON COLUMN R_TMP_FARMER_STAR.UPMID_RATE IS '上中等烟比例';
COMMENT ON COLUMN R_TMP_FARMER_STAR.MID_RATE IS '中部烟率';
COMMENT ON COLUMN R_TMP_FARMER_STAR.SALE_QUANTITY IS '交售烟叶数量（担）';
COMMENT ON COLUMN R_TMP_FARMER_STAR.SALE_AVG IS '交售均价';
COMMENT ON COLUMN R_TMP_FARMER_STAR.SALE_AVG_STAT_SUB IS '交售均价与烟站平均差值';
ALTER TABLE R_TMP_FARMER_STAR add column UP_COUC_AVG_SUB_INFO VARCHAR(128);
ALTER TABLE R_TMP_FARMER_STAR add column PER_MU_YIELD_INFO VARCHAR(128);
ALTER TABLE R_TMP_FARMER_STAR add column FOURC_RATE_INFO VARCHAR(128);
ALTER TABLE R_TMP_FARMER_STAR add column FOURC_COUC_AVG_SUB_INFO VARCHAR(128);
ALTER TABLE R_TMP_FARMER_STAR add column DAN_AVG_PRICE_INFO VARCHAR(128);
ALTER TABLE R_TMP_FARMER_STAR add column DAN_AVG_PRICE_AVG_INFO VARCHAR(128);
ALTER TABLE R_TMP_FARMER_STAR add column BUY_CNTRCT_RATE_INFO VARCHAR(128);
ALTER TABLE R_TMP_FARMER_STAR add column CNTRCT_PLNT_AREA_INFO VARCHAR(32);
ALTER TABLE R_TMP_FARMER_STAR add column CNTRCT_AREA_THREE_INFO VARCHAR(32);
ALTER TABLE R_TMP_FARMER_STAR add column UP_RATE_INFO VARCHAR(32);
ALTER TABLE R_TMP_FARMER_STAR add column MU_AVG_REVENUE_INFO VARCHAR(32);
ALTER TABLE R_TMP_FARMER_STAR add column MU_AVG_REVENUE_AVG_INFO VARCHAR(128);
ALTER TABLE R_TMP_FARMER_STAR add column SALE_QUANTITY_INFO VARCHAR(32);
ALTER TABLE R_TMP_FARMER_STAR add column SALE_AVG_STAT_SUB_INFO VARCHAR(100);
ALTER TABLE R_TMP_FARMER_STAR add column FRM_EDU_INFO VARCHAR(10);
ALTER TABLE R_TMP_FARMER_STAR add column PLNT_YEAR_INFO VARCHAR(20);
ALTER TABLE R_TMP_FARMER_STAR add column UPMID_RATE_INFO VARCHAR(32);
ALTER TABLE R_TMP_FARMER_STAR add column MID_RATE_INFO VARCHAR(32);
ALTER TABLE R_TMP_FARMER_STAR add column MIDUP_RATE_INFO VARCHAR(32);
ALTER TABLE R_TMP_FARMER_STAR add column FRM_AGE_INFO VARCHAR(20);
--
CREATE TABLE
    DCCELL.R_TMP_FARMER_STAR_EX01
    (
        FRM_FUND_UNIQUE_ID VARCHAR(32) PRIMARY KEY NOT NULL,
        FRM_CD VARCHAR(32),
        FRM_NAME VARCHAR(64),
        UP_VARIETY_RATE DECIMAL(24,6) DEFAULT 0,
        UP_VARIETY_RATE_INFO VARCHAR(256),
        UP_VARIETY_COUC_AVG_SUB DECIMAL(24,6) DEFAULT 0,
        UP_VARIETY_COUC_AVG_SUB_INFO VARCHAR(256),
        VAR_PER_MU_YIELD DECIMAL(24,6) DEFAULT 0,
        VAR_PER_MU_YIELD_INFO VARCHAR(256),
        FOURC_RATE DECIMAL(24,6) DEFAULT 0,
        FOURC_RATE_INFO VARCHAR(128),
        FOURC_COUC_AVG_SUB DECIMAL(24,6) DEFAULT 0,
        FOURC_COUC_AVG_SUB_INFO VARCHAR(256),
        VAR_DAN_AVG_PRICE DECIMAL(24,6) DEFAULT 0,
        VAR_DAN_AVG_PRICE_INFO VARCHAR(128),
        VAR_DAN_AVG_PRICE_COUC_AVG_SUB DECIMAL(24,6) DEFAULT 0,
        VAR_DAN_AVG_PRICE_COUC_AVG_SUB_INFO VARCHAR(128),
        BUY_CNTRCT_RATE_TWO_YEAR DECIMAL(24,6) DEFAULT 0,
        BUY_CNTRCT_RATE_TWO_YEAR_INFO VARCHAR(128),
        ZYF_PUR_RATE DECIMAL(24,6) DEFAULT 0,
        ZYF_PUR_RATE_INFO VARCHAR(256),
        XSJ_PUR_RATE DECIMAL(24,6) DEFAULT 0,
        XSJ_PUR_RATE_INFO VARCHAR(256),
        BF_PUR_RATE DECIMAL(24,6) DEFAULT 0,
        BF_PUR_RATE_INFO VARCHAR(256),
        DM_PUR_RATE DECIMAL(24,6) DEFAULT 0,
        DM_PUR_RATE_INFO VARCHAR(256),
        DGQC_COMP_RATE DECIMAL(24,6) DEFAULT 0,
        DGQC_COMP_RATE_INFO VARCHAR(128),
        YZ_IMP_RATE DECIMAL(24,6) DEFAULT 0,
        YZ_IMP_RATE_INFO VARCHAR(128),
        HK_IMP_RATE DECIMAL(24,6) DEFAULT 0,
        HK_IMP_RATE_INFO VARCHAR(128),
        SALE_HG_RATE DECIMAL(24,6) DEFAULT 0,
        SALE_HG_RATE_INFO VARCHAR(128),
        QUALITY_COMP DECIMAL(24,6) DEFAULT 0,
        QUALITY_COMP_INFO VARCHAR(128),
        HU_AVG_REVENUE_COUC_AVG_SUB DECIMAL(24,6) DEFAULT 0,
        HU_AVG_REVENUE_COUC_AVG_SUB_INFO VARCHAR(128),
        LAND_LEASE_YEAR DECIMAL(24,6) DEFAULT 0,
        LAND_LEASE_YEAR_INFO VARCHAR(128),
        PROV VARCHAR(32) DEFAULT '0',
        PROV_NAME VARCHAR(128),
        CITC VARCHAR(32) DEFAULT '0',
        CITC_NAME VARCHAR(128),
        COUC VARCHAR(32) DEFAULT '0',
        COUC_NAME VARCHAR(128),
        STAC VARCHAR(32) DEFAULT '0',
        STAC_NAME VARCHAR(128),
        SSTC VARCHAR(32) DEFAULT '0',
        SSTC_NAME VARCHAR(128),
        AREA_PROV VARCHAR(32) DEFAULT '0',
        AREA_PROV_NAME VARCHAR(128),
        AREA_CITC VARCHAR(32) DEFAULT '0',
        AREA_CITC_NAME VARCHAR(128),
        AREA_COUC VARCHAR(32) DEFAULT '0',
        AREA_COUC_NAME VARCHAR(128),
        AREA_TOWN VARCHAR(32) DEFAULT '0',
        TOWN_NAME VARCHAR(128),
        AREA_VAGE VARCHAR(32) DEFAULT '0',
        VAGE_NAME VARCHAR(128),
        AREA_GRUP VARCHAR(32) DEFAULT '0',
        GRUP_NAME VARCHAR(128),
        BUSINESS_YEAR DECIMAL(4,0)
    )IN DCCELL_SPACE_32K INDEX IN INDEX_SPACE;
    
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.FRM_FUND_UNIQUE_ID
IS
    '烟农ID';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.FRM_CD
IS
    '烟农编号';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.FRM_NAME
IS
    '烟农名称';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.UP_VARIETY_RATE
IS
    '上等烟比例（区分品种）';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.UP_VARIETY_RATE_INFO
IS
    '上等烟比例（区分品种)值来源说明';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.UP_VARIETY_COUC_AVG_SUB
IS
    '上等烟比例与县平均差值（区分品种）';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.VAR_PER_MU_YIELD
IS
    '亩产量差异值（区分品种）';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.FOURC_RATE
IS
    '4C比例（区分品种）';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.FOURC_COUC_AVG_SUB
IS
    '4C比例与县平均差值（区分品种）';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.VAR_DAN_AVG_PRICE
IS
    '担均价（区分品种）';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.VAR_DAN_AVG_COUC_AVG_SUB
IS
    '担均价与县平均差值（区分品种）';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.BUY_CNTRCT_RATE_TWO_YEAR
IS
    '合同履约率（最近两年）';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.ZYF_PUR_RATE
IS
    '专用肥购买率';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.XSJ_PUR_RATE
IS
    '硝酸钾购买率';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.BF_PUR_RATE
IS
    '饼肥购买率';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.DM_PUR_RATE
IS
    '地膜购买率';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.DGQC_COMP_RATE
IS
    '冬耕清残完成比例';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.YZ_IMP_RATE
IS
    '移栽执行率';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.HK_IMP_RATE
IS
    '烘烤执行率';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.SALE_HG_RATE
IS
    '交售合格率';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.QUALITY_COMP
IS
    '质量完成情况';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.HU_AVG_COUC_AVG_SUB
IS
    '户均种烟收入与县平均差值';
COMMENT ON COLUMN DCCELL.R_TMP_FARMER_STAR_EX01.LAND_LEASE_YEAR
IS
    '土地租赁年限';


----需增加字段长度（DB2脚本）
alter table DCCELL.R_TMP_FARMER_STAR_EX01 alter column VAR_DAN_AVG_PRICE_COUC_AVG_SUB_INFO set data type VARCHAR(256);
alter table DCCELL.R_TMP_FARMER_STAR_EX01 alter column FOURC_COUC_AVG_SUB_INFO  set data type VARCHAR(256);
alter table DCCELL.R_TMP_FARMER_STAR_EX01 alter column VAR_PER_MU_YIELD_INFO  set data type VARCHAR(256);
alter table DCCELL.R_TMP_FARMER_STAR_EX01 alter column UP_VARIETY_COUC_AVG_SUB_INFO  set data type VARCHAR(256);
alter table DCCELL.R_TMP_FARMER_STAR_EX01 alter column UP_VARIETY_RATE_INFO  set data type VARCHAR(256);
alter table DCCELL.R_TMP_FARMER_STAR_EX01 alter column ZYF_PUR_RATE_INFO  set data type VARCHAR(256);
alter table DCCELL.R_TMP_FARMER_STAR_EX01 alter column XSJ_PUR_RATE_INFO  set data type VARCHAR(256);
alter table DCCELL.R_TMP_FARMER_STAR_EX01 alter column BF_PUR_RATE_INFO  set data type VARCHAR(256);
alter table DCCELL.R_TMP_FARMER_STAR_EX01 alter column DM_PUR_RATE_INFO  set data type VARCHAR(256);


alter table DCCELL.R_TMP_FARMER_STAR_EX01 add column X2F_WGHT_RATE decimal(24,6);
alter table DCCELL.R_TMP_FARMER_STAR_EX01 add column C4F_WGHT_RATE decimal(24,6);
alter table DCCELL.R_TMP_FARMER_STAR_EX01 add column X2F_WGHT_RATE_INFO VARCHAR(128);
alter table DCCELL.R_TMP_FARMER_STAR_EX01 add column C4F_WGHT_RATE_INFO VARCHAR(128);

alter table DCCELL.R_TMP_FARMER_STAR_EX01 add column X2F_WGHT_RATE_COUC_SUB decimal(24,6);
alter table DCCELL.R_TMP_FARMER_STAR_EX01 add column C4F_WGHT_RATE_COUC_SUB decimal(24,6);
alter table DCCELL.R_TMP_FARMER_STAR_EX01 add column X2F_WGHT_RATE_COUC_SUB_INFO VARCHAR(128);
alter table DCCELL.R_TMP_FARMER_STAR_EX01 add column C4F_WGHT_RATE_COUC_SUB_INFO VARCHAR(128);

alter table DCCELL.R_TMP_FARMER_STAR alter column FRM_EDU_INFO set data type VARCHAR(20);


--增加打顶面积字段
ALTER TABLE DCCELL.R_PT_DT_FM_D ADD BEAT_TOP_AREA DECIMAL(24,6);
ALTER TABLE DCCELL.R_PT_DT_DV_D ADD BEAT_TOP_AREA DECIMAL(24,6);
ALTER TABLE DCCELL.R_PT_DT_CB_D ADD BEAT_TOP_AREA DECIMAL(24,6);

--增加施肥重量字段
ALTER TABLE DCCELL.R_PT_DT_FM_D ADD MANURE_WGHT DECIMAL(24,6);
ALTER TABLE DCCELL.R_PT_DT_DV_D ADD MANURE_WGHT DECIMAL(24,6);
ALTER TABLE DCCELL.R_PT_DT_CB_D ADD MANURE_WGHT DECIMAL(24,6);

--增加肥料名称字段
ALTER TABLE DCCELL.R_PT_DT_FM_D ADD MANURE_NAME VARCHAR(32);
ALTER TABLE DCCELL.R_PT_DT_DV_D ADD MANURE_NAME VARCHAR(32);
ALTER TABLE DCCELL.R_PT_DT_CB_D ADD MANURE_NAME VARCHAR(32);

--增加优化面积字段
ALTER TABLE DCCELL.R_PT_YY_GROW_FM_D ADD OPTM_AREA DECIMAL(24,6);
ALTER TABLE DCCELL.R_PT_YY_GROW_DV_D ADD OPTM_AREA DECIMAL(24,6);
ALTER TABLE DCCELL.R_PT_YY_GROW_CB_D ADD OPTM_AREA DECIMAL(24,6);

--增加用药浓度字段
ALTER TABLE DCCELL.R_PT_MEDICATE_FM_D ADD MEDICATE_DENSITY DECIMAL(24,6);
ALTER TABLE DCCELL.R_PT_MEDICATE_DV_D ADD MEDICATE_DENSITY DECIMAL(24,6);
ALTER TABLE DCCELL.R_PT_MEDICATE_CB_D ADD MEDICATE_DENSITY DECIMAL(24,6);





CREATE TABLE
    DCCELL.R_PT_MEDICATE_FM_D
    (
        MEDICATE_FM_D_ID VARCHAR(32) NOT NULL,
        BUSINESS_YEAR DECIMAL(4,0),
        BUSINESS_DATE TIMESTAMP,
        FARMER_ID VARCHAR(32),
        FARMER_CD VARCHAR(32),
        FARMER_NAME VARCHAR(64),
        FIELD_BLOCK_ID VARCHAR(32),
        FIELD_BLOCK_CD VARCHAR(32),
        FIELD_BLOCK_NAME VARCHAR(64),
        TECHNICIAN_ID VARCHAR(32),
        TECHNICIAN_NAME VARCHAR(64),
        DEFEND_TYPE VARCHAR(32),
        MEDICATE_TYPE VARCHAR(32),
        MEDICATE_AREA DECIMAL(24,6),
        MEDICATE_QTY DECIMAL(24,6),
        EFFECT_MEDICATE_QTY DECIMAL(24,6),
        ORG_CD VARCHAR(32) DEFAULT '0',
        ORG_NAME VARCHAR(128),
        PROV VARCHAR(32) DEFAULT '0',
        PROV_NAME VARCHAR(128),
        CITC VARCHAR(32) DEFAULT '0',
        CITC_NAME VARCHAR(128),
        COUC VARCHAR(32) DEFAULT '0',
        COUC_NAME VARCHAR(128),
        STAC VARCHAR(32) DEFAULT '0',
        STAC_NAME VARCHAR(128),
        SSTC VARCHAR(32) DEFAULT '0',
        SSTC_NAME VARCHAR(128),
        SLIN VARCHAR(32) DEFAULT '0',
        SLIN_NAME VARCHAR(128),
        AREA_CD VARCHAR(32) DEFAULT '0',
        AREA_NAME VARCHAR(128),
        AREA_PROV VARCHAR(32) DEFAULT '0',
        AREA_PROV_NAME VARCHAR(128),
        AREA_CITC VARCHAR(32) DEFAULT '0',
        AREA_CITC_NAME VARCHAR(128),
        AREA_COUC VARCHAR(32) DEFAULT '0',
        AREA_COUC_NAME VARCHAR(128),
        AREA_TOWN VARCHAR(32) DEFAULT '0',
        TOWN_NAME VARCHAR(128),
        AREA_VAGE VARCHAR(32) DEFAULT '0',
        VAGE_NAME VARCHAR(128),
        AREA_GRUP VARCHAR(32) DEFAULT '0',
        GRUP_NAME VARCHAR(128),
        SEND_STATE CHARACTER(1) DEFAULT '0',
        DATA_STATE CHARACTER(1) DEFAULT '1',
        MODIFY_TIME TIMESTAMP,
        SEND_TIME TIMESTAMP,
        PACKAGE_TIME TIMESTAMP,
        LAST_TIME TIMESTAMP DEFAULT CURRENT TIMESTAMP,
        CNTY VARCHAR(32) DEFAULT '0',
        CNTY_NAME VARCHAR(128),
        CNTY_UNIQUE VARCHAR(32) DEFAULT '0',
        PROV_UNIQUE VARCHAR(32) DEFAULT '0',
        CITC_UNIQUE VARCHAR(32) DEFAULT '0',
        COUC_UNIQUE VARCHAR(32) DEFAULT '0',
        STAC_UNIQUE VARCHAR(32) DEFAULT '0',
        SSTC_UNIQUE VARCHAR(32) DEFAULT '0',
        SLIN_UNIQUE VARCHAR(32) DEFAULT '0',
        AREA_CNTY VARCHAR(32) DEFAULT '0',
        AREA_CNTY_NAME VARCHAR(128),
        BEGIN_DATE TIMESTAMP,
        END_DATE TIMESTAMP,
        MEDICATE_TIME VARCHAR(32),
        MEDICATE_NAME VARCHAR(32),
        DISEASE_NAME VARCHAR(32),
        MEDICATE_DENSITY DECIMAL(24,6),
        CONSTRAINT PK_R_PT_MEDICATE_FM_D PRIMARY KEY (MEDICATE_FM_D_ID)
    )  IN DCCELL_SPACE INDEX IN INDEX_SPACE;
    
    
CREATE TABLE
    DCCELL.R_PT_MEDICATE_DV_D
    (
        MEDICATE_DV_D_ID VARCHAR(32) NOT NULL,
        BUSINESS_YEAR DECIMAL(4,0),
        BUSINESS_DATE TIMESTAMP,
        DEFEND_TYPE VARCHAR(32),
        MEDICATE_TYPE VARCHAR(32),
        MEDICATE_AREA DECIMAL(24,6),
        MEDICATE_QTY DECIMAL(24,6),
        EFFECT_MEDICATE_QTY DECIMAL(24,6),
        ORG_CD VARCHAR(32) DEFAULT '0',
        ORG_NAME VARCHAR(128),
        PROV VARCHAR(32) DEFAULT '0',
        PROV_NAME VARCHAR(128),
        CITC VARCHAR(32) DEFAULT '0',
        CITC_NAME VARCHAR(128),
        COUC VARCHAR(32) DEFAULT '0',
        COUC_NAME VARCHAR(128),
        STAC VARCHAR(32) DEFAULT '0',
        STAC_NAME VARCHAR(128),
        SSTC VARCHAR(32) DEFAULT '0',
        SSTC_NAME VARCHAR(128),
        SLIN VARCHAR(32) DEFAULT '0',
        SLIN_NAME VARCHAR(128),
        AREA_CD VARCHAR(32) DEFAULT '0',
        AREA_NAME VARCHAR(128),
        AREA_PROV VARCHAR(32) DEFAULT '0',
        AREA_PROV_NAME VARCHAR(128),
        AREA_CITC VARCHAR(32) DEFAULT '0',
        AREA_CITC_NAME VARCHAR(128),
        AREA_COUC VARCHAR(32) DEFAULT '0',
        AREA_COUC_NAME VARCHAR(128),
        AREA_TOWN VARCHAR(32) DEFAULT '0',
        TOWN_NAME VARCHAR(128),
        AREA_VAGE VARCHAR(32) DEFAULT '0',
        VAGE_NAME VARCHAR(128),
        AREA_GRUP VARCHAR(32) DEFAULT '0',
        GRUP_NAME VARCHAR(128),
        SEND_STATE CHARACTER(1) DEFAULT '0',
        DATA_STATE CHARACTER(1) DEFAULT '1',
        MODIFY_TIME TIMESTAMP,
        SEND_TIME TIMESTAMP,
        PACKAGE_TIME TIMESTAMP,
        LAST_TIME TIMESTAMP DEFAULT CURRENT TIMESTAMP,
        CNTY VARCHAR(32) DEFAULT '0',
        CNTY_NAME VARCHAR(128),
        CNTY_UNIQUE VARCHAR(32) DEFAULT '0',
        PROV_UNIQUE VARCHAR(32) DEFAULT '0',
        CITC_UNIQUE VARCHAR(32) DEFAULT '0',
        COUC_UNIQUE VARCHAR(32) DEFAULT '0',
        STAC_UNIQUE VARCHAR(32) DEFAULT '0',
        SSTC_UNIQUE VARCHAR(32) DEFAULT '0',
        SLIN_UNIQUE VARCHAR(32) DEFAULT '0',
        AREA_CNTY VARCHAR(32) DEFAULT '0',
        AREA_CNTY_NAME VARCHAR(128),
        MEDICATE_DENSITY DECIMAL(24,6),
        CONSTRAINT PK_R_PT_MEDICATE_DV_D PRIMARY KEY (MEDICATE_DV_D_ID)
    ) IN DCCELL_SPACE INDEX IN INDEX_SPACE;
    
CREATE TABLE
    R_PT_MEDICATE_CB_D
    (
        MEDICATE_CB_D_ID VARCHAR(32) NOT NULL,
        BUSINESS_YEAR DECIMAL(4,0),
        BUSINESS_DATE TIMESTAMP,
        DEFEND_TYPE VARCHAR(32),
        MEDICATE_TYPE VARCHAR(32),
        MEDICATE_AREA DECIMAL(24,6),
        MEDICATE_QTY DECIMAL(24,6),
        EFFECT_MEDICATE_QTY DECIMAL(24,6),
        ORG_CD VARCHAR(32) DEFAULT '0',
        ORG_NAME VARCHAR(128),
        PROV VARCHAR(32) DEFAULT '0',
        PROV_NAME VARCHAR(128),
        CITC VARCHAR(32) DEFAULT '0',
        CITC_NAME VARCHAR(128),
        COUC VARCHAR(32) DEFAULT '0',
        COUC_NAME VARCHAR(128),
        STAC VARCHAR(32) DEFAULT '0',
        STAC_NAME VARCHAR(128),
        SSTC VARCHAR(32) DEFAULT '0',
        SSTC_NAME VARCHAR(128),
        SLIN VARCHAR(32) DEFAULT '0',
        SLIN_NAME VARCHAR(128),
        SEND_STATE CHARACTER(1) DEFAULT '0',
        DATA_STATE CHARACTER(1) DEFAULT '1',
        MODIFY_TIME TIMESTAMP,
        SEND_TIME TIMESTAMP,
        PACKAGE_TIME TIMESTAMP,
        LAST_TIME TIMESTAMP DEFAULT CURRENT TIMESTAMP,
        CNTY VARCHAR(32) DEFAULT '0',
        CNTY_NAME VARCHAR(128),
        CNTY_UNIQUE VARCHAR(32) DEFAULT '0',
        PROV_UNIQUE VARCHAR(32) DEFAULT '0',
        CITC_UNIQUE VARCHAR(32) DEFAULT '0',
        COUC_UNIQUE VARCHAR(32) DEFAULT '0',
        STAC_UNIQUE VARCHAR(32) DEFAULT '0',
        SSTC_UNIQUE VARCHAR(32) DEFAULT '0',
        SLIN_UNIQUE VARCHAR(32) DEFAULT '0',
        AREA_CNTY VARCHAR(32) DEFAULT '0',
        AREA_CNTY_NAME VARCHAR(128),
        MEDICATE_DENSITY DECIMAL(24,6),
        CONSTRAINT PK_R_PT_MEDICATE_CB_D PRIMARY KEY (MEDICATE_CB_D_ID)
    ) IN DCCELL_SPACE INDEX IN INDEX_SPACE;
    
    
--由于表空间不够， 先删除表，然后重建到32K表空间里
DROP TABLE DCCELL.R_PT_TRANSPLANT_FM_D;

CREATE TABLE
    DCCELL.R_PT_TRANSPLANT_FM_D
    (
        TRANSPLANT_FM_D_ID VARCHAR(32) NOT NULL,
        BUSINESS_YEAR DECIMAL(4,0),
        BUSINESS_DATE TIMESTAMP,
        LEAF_TYPE_CD VARCHAR(32),
        LEAF_TYPE_NAME VARCHAR(64),
        LEAF_VARIETY_CD VARCHAR(32),
        LEAF_VARIETY_NAME VARCHAR(64),
        TRANSPLANT_QTY DECIMAL(12,0),
        TRANSPLANT_AREA DECIMAL(24,6) DEFAULT 0,
        TY_AREA DECIMAL(24,6) DEFAULT 0,
        DY_AREA DECIMAL(24,6) DEFAULT 0,
        UNDER_FILM_AREA DECIMAL(24,6) DEFAULT 0,
        PROPESS_AREA DECIMAL(24,6) DEFAULT 0,
        AVG_PLANT_DENSITY DECIMAL(24,6) DEFAULT 0,
        CENSUS_QTY DECIMAL(24,6) DEFAULT 0,
        CENSUS_AREA DECIMAL(24,6) DEFAULT 0,
        AREA_CD VARCHAR(32) DEFAULT '0',
        AREA_NAME VARCHAR(128),
        AREA_PROV VARCHAR(32) DEFAULT '0',
        AREA_PROV_NAME VARCHAR(128),
        AREA_CITC VARCHAR(32) DEFAULT '0',
        AREA_CITC_NAME VARCHAR(128),
        AREA_COUC VARCHAR(32) DEFAULT '0',
        AREA_COUC_NAME VARCHAR(128),
        AREA_TOWN VARCHAR(32) DEFAULT '0',
        TOWN_NAME VARCHAR(128),
        AREA_VAGE VARCHAR(32) DEFAULT '0',
        VAGE_NAME VARCHAR(128),
        AREA_GRUP VARCHAR(32) DEFAULT '0',
        GRUP_NAME VARCHAR(128),
        ORG_CD VARCHAR(32) DEFAULT '0',
        ORG_NAME VARCHAR(128),
        PROV VARCHAR(32) DEFAULT '0',
        PROV_NAME VARCHAR(128),
        CITC VARCHAR(32) DEFAULT '0',
        CITC_NAME VARCHAR(128),
        COUC VARCHAR(32) DEFAULT '0',
        COUC_NAME VARCHAR(128),
        STAC VARCHAR(32) DEFAULT '0',
        STAC_NAME VARCHAR(128),
        SSTC VARCHAR(32) DEFAULT '0',
        SSTC_NAME VARCHAR(128),
        SLIN VARCHAR(32) DEFAULT '0',
        SLIN_NAME VARCHAR(128),
        SEND_STATE CHARACTER(1) DEFAULT '0',
        DATA_STATE CHARACTER(1) DEFAULT '1',
        MODIFY_TIME TIMESTAMP,
        SEND_TIME TIMESTAMP,
        PACKAGE_TIME TIMESTAMP,
        LAST_TIME TIMESTAMP DEFAULT CURRENT TIMESTAMP,
        FARMER_ID VARCHAR(32),
        FARMER_CD VARCHAR(32),
        FARMER_NAME VARCHAR(64),
        FIELD_BLOCK_ID VARCHAR(32),
        FIELD_BLOCK_CD VARCHAR(32),
        FIELD_BLOCK_NAME VARCHAR(64),
        TECHNICIAN_ID VARCHAR(32),
        TECHNICIAN_NAME VARCHAR(64),
        IS_AREA_TALLY CHARACTER(1),
        IS_LOCATION_TALLY CHARACTER(1),
        DIFF_TRANSPLANT_AREA DECIMAL(24,6) DEFAULT 0,
        DEEP_TRANSPLANT_AREA DECIMAL(24,6) DEFAULT 0,
        CNTY VARCHAR(32) DEFAULT '0',
        CNTY_NAME VARCHAR(128),
        CNTY_UNIQUE VARCHAR(32) DEFAULT '0',
        PROV_UNIQUE VARCHAR(32) DEFAULT '0',
        CITC_UNIQUE VARCHAR(32) DEFAULT '0',
        COUC_UNIQUE VARCHAR(32) DEFAULT '0',
        STAC_UNIQUE VARCHAR(32) DEFAULT '0',
        SSTC_UNIQUE VARCHAR(32) DEFAULT '0',
        SLIN_UNIQUE VARCHAR(32) DEFAULT '0',
        AREA_CNTY VARCHAR(32) DEFAULT '0',
        AREA_CNTY_NAME VARCHAR(128),
        FIELD_BLOCK_TOWN_NAME VARCHAR(32),
        ADDR VARCHAR(32),
        FILE_GROUP_ID VARCHAR(32),
        BEGIN_DATE TIMESTAMP,
        END_DATE TIMESTAMP , 
        WORK_EFFECT_EVAL VARCHAR(16),
        LINE_DISTANCE VARCHAR(16),
        ONE_DISTANCE VARCHAR(16),
        BEGIN_DATE TIMESTAMP,
        CONSTRAINT PK_R_PT_TRANSPLANT_FM_D PRIMARY KEY (TRANSPLANT_FM_D_ID)
    ) IN DCCELL_SPACE_32K INDEX IN INDEX_SPACE ;


--移栽加工表增加常德梳理出来的相关字段信息
alter table R_PT_TRANSPLANT_FM_D add column BEGIN_DATE TIMESTAMP ;
alter table R_PT_TRANSPLANT_FM_D add column END_DATE TIMESTAMP ;
alter table R_PT_TRANSPLANT_FM_D add column WORK_EFFECT_EVAL VARCHAR(16);
alter table R_PT_TRANSPLANT_FM_D add column LINE_DISTANCE VARCHAR(16);
alter table R_PT_TRANSPLANT_FM_D add column ONE_DISTANCE VARCHAR(16);
alter table R_PT_TRANSPLANT_CB_D add column BEGIN_DATE TIMESTAMP ;
alter table R_PT_TRANSPLANT_CB_D add column END_DATE TIMESTAMP ;
alter table R_PT_TRANSPLANT_CB_D add column WORK_EFFECT_EVAL VARCHAR(16);
alter table R_PT_TRANSPLANT_CB_D add column LINE_DISTANCE VARCHAR(16);
alter table R_PT_TRANSPLANT_CB_D add column ONE_DISTANCE VARCHAR(16);
alter table R_PT_TRANSPLANT_DV_D add column BEGIN_DATE TIMESTAMP ;
alter table R_PT_TRANSPLANT_DV_D add column END_DATE TIMESTAMP ;
alter table R_PT_TRANSPLANT_DV_D add column WORK_EFFECT_EVAL VARCHAR(16);
alter table R_PT_TRANSPLANT_DV_D add column LINE_DISTANCE VARCHAR(16);
alter table R_PT_TRANSPLANT_DV_D add column ONE_DISTANCE VARCHAR(16);

--起垄加工表增加常德梳理出来的相关字段信息
alter table R_PT_PREPAR_FM_D add column IS_HIGH_STAND VARCHAR(16);
alter table R_PT_PREPAR_FM_D add column WORK_EFFECT_EVAL VARCHAR(16);
alter table R_PT_PREPAR_FM_D add column IS_PROPESS VARCHAR(16);
alter table R_PT_PREPAR_FM_D add column BEGIN_DATE TIMESTAMP ;
alter table R_PT_PREPAR_FM_D add column END_DATE TIMESTAMP ;
alter table R_PT_PREPAR_FM_D add column SERV_ORG_ID VARCHAR(32);
alter table R_PT_PREPAR_CB_D add column IS_HIGH_STAND VARCHAR(16);
alter table R_PT_PREPAR_CB_D add column WORK_EFFECT_EVAL VARCHAR(16);
alter table R_PT_PREPAR_CB_D add column IS_PROPESS VARCHAR(16);
alter table R_PT_PREPAR_CB_D add column BEGIN_DATE TIMESTAMP ;
alter table R_PT_PREPAR_CB_D add column END_DATE TIMESTAMP ;
alter table R_PT_PREPAR_DV_D add column IS_HIGH_STAND VARCHAR(16);
alter table R_PT_PREPAR_DV_D add column WORK_EFFECT_EVAL VARCHAR(16);
alter table R_PT_PREPAR_DV_D add column IS_PROPESS VARCHAR(16);
alter table R_PT_PREPAR_DV_D add column BEGIN_DATE TIMESTAMP ;
alter table R_PT_PREPAR_DV_D add column END_DATE TIMESTAMP ;

--覆膜加工表增加常德梳理出来的相关字段信息
alter table R_PT_VELUM_FM_D add column VELUM_EFFTET VARCHAR(16);
alter table R_PT_VELUM_FM_D add column WORK_EFFECT_EVAL VARCHAR(16);
alter table R_PT_VELUM_FM_D add column BEGIN_DATE TIMESTAMP ;
alter table R_PT_VELUM_FM_D add column END_DATE TIMESTAMP ;
alter table R_PT_VELUM_CB_D add column VELUM_EFFTET VARCHAR(16);
alter table R_PT_VELUM_CB_D add column WORK_EFFECT_EVAL VARCHAR(16);
alter table R_PT_VELUM_CB_D add column BEGIN_DATE TIMESTAMP ;
alter table R_PT_VELUM_CB_D add column END_DATE TIMESTAMP ;
alter table R_PT_VELUM_DV_D add column VELUM_EFFTET VARCHAR(16);
alter table R_PT_VELUM_DV_D add column WORK_EFFECT_EVAL VARCHAR(16);
alter table R_PT_VELUM_DV_D add column BEGIN_DATE TIMESTAMP ;
alter table R_PT_VELUM_DV_D add column END_DATE TIMESTAMP ;

--大田植保加工表增加常德梳理出来的相关字段信息
alter table R_PT_DT_FM_D add column BEAT_TOP_OPPORT VARCHAR(16);
alter table R_PT_DT_FM_D add column BEAT_TOP_LEAF_QTY_EK VARCHAR(16);
alter table R_PT_DT_FM_D add column WORK_EFFECT_EVAL VARCHAR(16);
alter table R_PT_DT_FM_D add column BEGIN_DATE TIMESTAMP ;
alter table R_PT_DT_FM_D add column END_DATE TIMESTAMP ;


--加工总量主表
--drop table R_PT_MT_BAKE_RESULT_MAS;
CREATE TABLE R_PT_MT_BAKE_RESULT_MAS (
  PT_MT_BAKE_RESULT_MAS_ID VARCHAR(32)   PRIMARY KEY  NOT NULL ,
  ORG_UNIQUE_CD         VARCHAR(32),
  BUSINESS_YEAR         DECIMAL(4),
   PROV                 VARCHAR(32)            DEFAULT '0',
   PROV_NAME            VARCHAR(128),
   CITC                 VARCHAR(32)            DEFAULT '0',
   CITC_NAME            VARCHAR(128),
   COUC                 VARCHAR(32)            DEFAULT '0',
   COUC_NAME            VARCHAR(128),
   STAC                 VARCHAR(32)            DEFAULT '0',
   STAC_NAME            VARCHAR(128),
   SSTC                 VARCHAR(32)            DEFAULT '0',
   SSTC_NAME            VARCHAR(128),
   SLIN                 VARCHAR(32)            DEFAULT '0',
   SLIN_NAME            VARCHAR(128),
   CNTY                 VARCHAR(32)            DEFAULT '0',-- 国家局维度，org_cd
   CNTY_NAME            VARCHAR(128),                      -- 国家局维度，名称
   CNTY_UNIQUE          VARCHAR(32)            DEFAULT '0',-- 国家局维度，ORG_UNIQUE_CD
   PROV_UNIQUE          VARCHAR(32)            DEFAULT '0',-- 省，ORG_UNIQUE_CD
   CITC_UNIQUE          VARCHAR(32)            DEFAULT '0',-- 市，ORG_UNIQUE_CD
   COUC_UNIQUE          VARCHAR(32)            DEFAULT '0',-- 县，ORG_UNIQUE_CD
   STAC_UNIQUE          VARCHAR(32)            DEFAULT '0',-- 站，ORG_UNIQUE_CD
   SSTC_UNIQUE          VARCHAR(32)            DEFAULT '0',-- 点，ORG_UNIQUE_CD
   SLIN_UNIQUE          VARCHAR(32)            DEFAULT '0',-- 线，ORG_UNIQUE_CD
   TOWN_UNIQUE_CD       VARCHAR(32) DEFAULT '0',--乡
   VILL_UNIQUE_CD       VARCHAR(32) DEFAULT '0',--村
   LEAF_GUIDER_ID       VARCHAR(32),
   LEAF_GUIDER_NAME     VARCHAR(64),
   FRM_CD               VARCHAR(32),
   FRM_NAME             VARCHAR(64),
   LEAF_VARIETY_CD      VARCHAR(32),
   LEAF_VARIETY_NAME    VARCHAR(64),
   LEAF_SITE_TYPE       VARCHAR(10),
   TOTAL_BAKE_WGHT      DECIMAL(31,8),
    SITE_TOTAL_AREA     DECIMAL(31,8),
  PER_MU                DECIMAL(31,8),   --亩产
  TOTAL_PRODUCTION      DECIMAL(31,8),   --总产
  LAST_TIME             TIMESTAMP,
  SUMMARY_TYPE          VARCHAR(10),       --总量汇总类型
  DATA_STATE            CHAR(1)  DEFAULT '1'
) IN DCCELL_SPACE INDEX IN INDEX_SPACE ;


--加工明细等级占比等信息
--DROP TABLE R_PT_MT_BAKE_RESULT_DETAIL;
CREATE TABLE R_PT_MT_BAKE_RESULT_DETAIL (
  PT_MT_BAKE_RESULT_DETAIL_ID  VARCHAR(32) PRIMARY KEY  NOT NULL,
  ORG_UNIQUE_CD                VARCHAR(32),
  BUSINESS_YEAR                DECIMAL(4),
  PROV                         VARCHAR(32) DEFAULT '0',
  PROV_NAME                    VARCHAR(128),
  CITC                         VARCHAR(32) DEFAULT '0',
  CITC_NAME                    VARCHAR(128),
  COUC                         VARCHAR(32) DEFAULT '0',
  COUC_NAME                    VARCHAR(128),
  STAC                         VARCHAR(32) DEFAULT '0',
  STAC_NAME                    VARCHAR(128),
  SSTC                         VARCHAR(32) DEFAULT '0',
  SSTC_NAME                    VARCHAR(128),
  SLIN                         VARCHAR(32) DEFAULT '0',
  SLIN_NAME                    VARCHAR(128),
  CNTY                         VARCHAR(32) DEFAULT '0', -- 国家局维度，org_cd
  CNTY_NAME                    VARCHAR(128), -- 国家局维度，名称
  CNTY_UNIQUE                  VARCHAR(32) DEFAULT '0', -- 国家局维度，ORG_UNIQUE_CD
  PROV_UNIQUE                  VARCHAR(32) DEFAULT '0', -- 省，ORG_UNIQUE_CD
  CITC_UNIQUE                  VARCHAR(32) DEFAULT '0', -- 市，ORG_UNIQUE_CD
  COUC_UNIQUE                  VARCHAR(32) DEFAULT '0', -- 县，ORG_UNIQUE_CD
  STAC_UNIQUE                  VARCHAR(32) DEFAULT '0', -- 站，ORG_UNIQUE_CD
  SSTC_UNIQUE                  VARCHAR(32) DEFAULT '0', -- 点，ORG_UNIQUE_CD
  SLIN_UNIQUE                  VARCHAR(32) DEFAULT '0', -- 线，ORG_UNIQUE_CD
  TOWN_UNIQUE_CD               VARCHAR(32) DEFAULT '0',--乡
  VILL_UNIQUE_CD               VARCHAR(32) DEFAULT '0',--村
  LEAF_GUIDER_ID               VARCHAR(32),
  LEAF_GUIDER_NAME             VARCHAR(64),
  FRM_CD                       VARCHAR(32),
  FRM_NAME                     VARCHAR(64),
  LEAF_VARIETY_CD              VARCHAR(32),
  LEAF_VARIETY_NAME            VARCHAR(64),
  LEAF_SITE_TYPE               VARCHAR(10),
  LEAF_TYPE_CD                 VARCHAR(32),
  LEAF_TYPE_NAME               VARCHAR(32),
  LEAF_POSITION_CD             VARCHAR(32),
  LEAF_POSITION_NAME           VARCHAR(32),
  LEAF_LEVEL_CD                VARCHAR(32),
  LEAF_LEVEL_NO                VARCHAR(32),
  LEAF_LEVEL_NAME              VARCHAR(32),
  BAKE_WGHT                    DECIMAL(31, 8),
  LEAF_GUIDE_TOTAL_BAKE_WGHT   DECIMAL(31,8),
  BAKE_RADIO                   DECIMAL(31,8),
  LEVEL_GUIDER_TOTAL_BAKE_WGHT DECIMAL(31,8),
  LAST_TIME                    TIMESTAMP,
  SUMMARY_TYPE                 VARCHAR(10),       --总量汇总类型
  DATA_STATE                   CHAR(1)  DEFAULT '1'
) IN DCCELL_SPACE INDEX IN INDEX_SPACE ;



--创建烟农数据采集与督导结果关系表
  CREATE TABLE
    DCCELL.R_PT_DC_WC_RELA_D
    (
        RELA_D_ID VARCHAR(32) PRIMARY Key NOT NULL,
        BUSINESS_YEAR     DECIMAL(4,0),
        STAGE_NAME        VARCHAR(64),
        FARMER_ID         VARCHAR(32),
        FARMER_CD         VARCHAR(32),
        FARMER_NAME       VARCHAR(64),
        DC_CLT_OBJ_ID     VARCHAR(32),
        DC_CLT_OBJ_CD     VARCHAR(32),
        DC_CLT_OBJ_NAME   VARCHAR(64),
        TECHNICIAN_ID     VARCHAR(32),
        TECHNICIAN_NAME   VARCHAR(64),
        BUSINESS_DATE     TIMESTAMP,
        WC_DATE           TIMESTAMP,
        WC_ORG_CD         VARCHAR(32),
        WC_ORG_NAME       VARCHAR(64),
        WC_PSN_ID         VARCHAR(32),
        WC_PSN_NAME       VARCHAR(64),
        WC_PROBLEM        VARCHAR(255),
        WC_IMPORVE_METHOD VARCHAR(255),
        SEND_STATE CHARACTER(1) DEFAULT '0',
        DATA_STATE CHARACTER(1) DEFAULT '1',
        ORG_CD VARCHAR(32) DEFAULT '0',
        ORG_NAME VARCHAR(128),
        PROV VARCHAR(32) DEFAULT '0',
        PROV_NAME VARCHAR(128),
        CITC VARCHAR(32) DEFAULT '0',
        CITC_NAME VARCHAR(128),
        COUC VARCHAR(32) DEFAULT '0',
        COUC_NAME VARCHAR(128),
        STAC VARCHAR(32) DEFAULT '0',
        STAC_NAME VARCHAR(128),
        SSTC VARCHAR(32) DEFAULT '0',
        SSTC_NAME VARCHAR(128),
        SLIN VARCHAR(32) DEFAULT '0',
        SLIN_NAME VARCHAR(128),                
        AREA_CD VARCHAR(32) DEFAULT '0',
        AREA_NAME VARCHAR(128),
        AREA_PROV VARCHAR(32) DEFAULT '0',
        AREA_PROV_NAME VARCHAR(128),
        AREA_CITC VARCHAR(32) DEFAULT '0',
        AREA_CITC_NAME VARCHAR(128),
        AREA_COUC VARCHAR(32) DEFAULT '0',
        AREA_COUC_NAME VARCHAR(128),
        AREA_TOWN VARCHAR(32) DEFAULT '0',
        TOWN_NAME VARCHAR(128),
        AREA_VAGE VARCHAR(32) DEFAULT '0',
        VAGE_NAME VARCHAR(128),
        AREA_GRUP VARCHAR(32) DEFAULT '0',
        GRUP_NAME VARCHAR(128),
        CLEAN_AREA DECIMAL(24,6) DEFAULT 0,
        CNTY VARCHAR(32) DEFAULT '0',
        CNTY_NAME VARCHAR(128),
        CNTY_UNIQUE VARCHAR(32) DEFAULT '0',
        PROV_UNIQUE VARCHAR(32) DEFAULT '0',
        CITC_UNIQUE VARCHAR(32) DEFAULT '0',
        COUC_UNIQUE VARCHAR(32) DEFAULT '0',
        STAC_UNIQUE VARCHAR(32) DEFAULT '0',
        SSTC_UNIQUE VARCHAR(32) DEFAULT '0',
        SLIN_UNIQUE VARCHAR(32) DEFAULT '0',
        AREA_CNTY VARCHAR(32) DEFAULT '0',
        AREA_CNTY_NAME VARCHAR(128),
        PACKAGE_TIME TIMESTAMP,
        MODIFY_TIME TIMESTAMP,
        SEND_TIME TIMESTAMP,
        LAST_TIME TIMESTAMP DEFAULT CURRENT Timestamp        
    ) IN DCCELL_SPACE_32K INDEX IN INDEX_SPACE;
